### ISSUE TITLE
Tapping the avatar of a communication partner in a DM leads to different screens depending on context

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#1120]
### Steps to reproduce

1. Enter a DM
2. Click on the avatar at the top of the DM
3. Click on an avatar in the communication
4. Compare

#### What did you expect?
Ending up on the same identical profile page

#### What happened instead?
Seeing two different pages with different options

https://github.com/vector-im/element-x-android/assets/640121/6809538d-e95b-42c3-b987-27770d98b150

### Your phone model

Pixel 5

### Operating system version

Android 13

### Application version and app store

0.1.4-nightly

### Homeserver

Matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
It seems like on iOS they just remove the avatar from the user messages in DMs, so we should probably do the same, which would take care of this issue too.

**Comment by kongo09** [comment]
That would be what all other messengers do for DMs, so +1

**Comment by manuroe** [comment]
We do not display anymore user avatars in a DM timeline. This weird use case cannot happen anymore.
