### ISSUE TITLE
Homeserver url field apparently requires https:// prefix

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-android#1144]
### Steps to reproduce

1. Change homeserver at login
2. Enter `element.io` into the server box
3. According to @rxl881 it causes weird errors unless you prefix with https://

#### What did you expect?

no https:// prefix needed

### Application version and app store

0.1.2 (40001020) playstore

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
I do not reproduce the issue. When entering `element.io`, the homeserver `element.io` is displayed in the list as a valid result:

<img width="270" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/d32e6b5c-c357-45fc-9c6b-7bf58c66790f">

The application will propose to use the homeserver, even if no `.well-known` file is detected and valid only if the url is complete though.

For instance with `nochance.org`:

<img width="268" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/bf8b3719-8d73-4193-8574-eb3390a5d10c">

<img width="267" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/8f16012b-011c-4d46-82bb-c890271fe6fd">

But when selecting `nochance.org`, this error will be displayed:

<img width="276" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/b50cf773-1f80-4764-ad01-6d7868b1d27f">

@rxl881 do you repro with the latest nightly? We will release a new version in the AppStore very soon, you can try to repro on this one.

**Comment by rxl881** [comment]
I think that this was a combination of me using the wrong homesaerver domain and also a dark theme bug whereby I couldn't see the results of the search. 

Specifically, I was trying to log in to the vector.modular.im homeserver (not element.io). I forgot that it was on a modular subdomain and instead was trying to log in with vector.im, which returned no results (that I could see). I then tried https://vector.im, which did return a result which I then clicked on, but obviously failed to log me in against. I guess that matches with the screenshot that you provided above (as there was no .well-known for the domain that I specified, but it tried anyway when I specified the full URL). 

More of a UX issue, but I was a bit confused by the phrase "search term or domain address" ... I get what we're going for here (trying to make it less technical), but it seemed a bit unclear when I was looking to input the "homeserver name" or "homeserver domain", which would be a more precise.

**Comment by bmarty** [comment]
For the wording, this is a product team's decision, we are just integrating it. CC @VolkerJunginger if we want to improve this.

**Comment by anoadragon453** [comment]
Should this get an `X-Needs-Product` label?

**Comment by spaetz** [comment]
Given the server field does not need https:// prefixed, can this be closed? The wording is really a different issue.
