### ISSUE TITLE
[Element Call] Create call screen UI

### ISSUE THREAD

**Issue by jmartinesp** [element-hq/element-x-android#1155]
# List of changes needed

- [ ] Create a new screen for calls. It's probably better if it's in a new `Activity`, as the PiP feature we want to implement in the future would be hard to achieve in our single activity approach.
- [ ] Add a WebView to this screen. The WebView should handle camera and microphone permissions, have javascript execution enabled and be able to store data locally.
- [ ] Make this WebView load the provided call URL. The mechanism for generating this URL doesn't exist when this issue was created, so you can replace it with some Element Call url.
- [ ] Keep the WebView alive while the app is in background mode or the device is locked. A foreground service allows this to happen.
- [ ] While the WebView is displayed, the screen should stay on and multimedia should be either muted or paused. It's unclear if we should resume this multimedia after the call, but we should restore the media volume if we modify it.

The designs for this are still TBD.

There is a very crude implementation of this in https://github.com/vector-im/element-x-android/tree/feature/jme/element-call-tests that we can use as a base for a proper implementation.

**Comment by bmarty** [comment]
I think this is fully done, please re-open if it's not the case. Thanks!
