### ISSUE TITLE
[Element Call] Integrate Widget API with WebView

### ISSUE THREAD

**Issue by jmartinesp** [element-hq/element-x-android#1156]
Depends on #1155 .

The Widget API is a feature meant to deliver messages in JSON format between the Rust SDK and any implemented widget, in this case, the Element Call webview. You can find the PR for the API skeleton [here](https://github.com/matrix-org/matrix-rust-sdk/pull/2453) and the actual implementation [here](https://github.com/matrix-org/matrix-rust-sdk/pull/2465) (to be merged when this issue was created).

The actual changes needed might need to be edited as we have more info of the implementation details.

## Changes needed

- [ ] Run the widget API from the app, using any FFI API available.
- [ ] Read messages from the Widget API using the `Comms` API inside `Widget`, pass it to the WebView by evaluating javascript that sends the JSON to some event handler (neither of these parts were ready when this was written).
- [ ] Also do the opposite: add a callback / event listener to the WebView to relay some JSON messages from it to the Widget API using the same `Comms`.

**Comment by bmarty** [comment]
I think this is fully done, please re-open if it's not the case. Thanks!
