### ISSUE TITLE
Overall Performance 

### ISSUE THREAD

**Issue by ganfra** [element-hq/element-x-android#1245]
Look at performance issues when opening/closing rooms multiple time.
Ram and cpu is growing and never gets down at some point. Looks like it could come from RoomMember loading.

**Comment by jmartinesp** [comment]
We just got a couple of [rageshakes](https://github.com/vector-im/element-x-android-rageshakes/issues/458) that might be related, at least to the RAM usage, since apparently we're keeping *51200*  references to Rust items at some point and JNA just crashes.

**Comment by ganfra** [comment]
This might be related to room members loading, but not 100% sure.
https://github.com/element-hq/element-x-android/issues/851

**Comment by spaetz** [comment]
Given it's a year later and performance seems to be quite OK, can this one be closed?
