### ISSUE TITLE
Seperate "Friends" and "Rooms" into their resp. tabs?

### ISSUE THREAD

**Issue by Icy-Thought** [element-hq/element-x-android#1276]
#### What would you like to do?

I would like for the Element-X team to separate the "Friends" from the "Rooms" chat buffers.

#### Why would you like to do it?

To keep it short & simple,
1. Reduce the amount of time required for navigating contacts.

#### How would you like to achieve it?

Adapt the separated columns for both "People" and "Rooms" in element-web in a tab-like format. And to make the navigation even more fluid, we could provide swipe support (RTL and LTR) for users to easily navigate between the "Friends" and "Rooms" tabs.

### Are you willing to provide a PR?

No

**Comment by spiffyfrodo** [comment]
I would like something similar. Right now I see an option for Filters on the Android phone app and three tabs appear:
All | Unread | People

I wonder if its possible to have:
Rooms | Unread | People

Or have the option to choose between these two views?

Right now having people mixed with rooms makes the user experience, where I am working, "messy." I am working with non-tech-savvy older horticulturists for context... But as a tech-savvy guy, I would still like to see this option, if possible and permitted. :)

**Comment by wapsi** [comment]
This is definitely needed! I really like the separation between p2p rooms and normal rooms in the "traditional" Element version.

**Comment by defini-tiv** [comment]
For me this never made sense tbh.
In practice it adds more steps to navigation and makes it less intuitive.
Also most other instant messengers don't seem to see a need for it.
For me #2383 would be way more helpful eventually.

**Comment by bmarty** [comment]
What are implementing a filtering of rooms instead of tab. It's now possible to select "People" or "Room" to filter room, using the nightly (the feature is not yet activated in prod). You have to enable the feature in the flag for now, it's work in progress.
