### ISSUE TITLE
Killing app and starting it results in empty room list and eternal syncing

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#1306]
### Steps to reproduce

1. Stop app on Android (but not clear data)
2. Restart app

#### What did you expect?
See room list instantly

#### What happened instead?
See empty roomlist with eternal spinning of sync

### Your phone model

Pixel 5

### Operating system version

Android 13

### Application version and app store

0.1.7-nightly

### Homeserver

element.io

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by kongo09** [comment]
https://github.com/vector-im/element-x-android/assets/640121/23322b6b-25bc-4c40-b7e2-11dd4318f016

**Comment by manuroe** [comment]
I hope it does not happen anymore. Please reopen if it is still a problem.
