### ISSUE TITLE
Verification fails when starting from desktop

### ISSUE THREAD

**Issue by Aquathing** [element-hq/element-x-android#1311]
### Steps to reproduce

1. Login and see the "Verify new device" banner
2. Accept the request on Element Desktop, and click Start there instead of EX

I can't reproduce this every time, as you can see in the logs it took some tries to reproduce it.

#### What did you expect?
Verification process goes through as usual

#### What happened instead?
Verification gets canceled on both devices

### Your phone model

Nothing Phone 1

### Operating system version

Android 13 Nothing OS 2.0.2

### Application version and app store

App Tester 0.1.7-nightly (40001070)

### Homeserver

Synapse v1.89

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by manuroe** [comment]
@Aquathing I am closing this issue because we did several improvements on this topic. Please reopen the issue if you notice the problem again.
