### ISSUE TITLE
To check: receiving push without eventId or roomId.

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#1349]
Currently pushes like this are ignored by the app, but this is somehow unexpected:

<img width="1134" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/b5d06783-26cc-4366-87b2-d086f685e37b">

**Comment by manuroe** [comment]
Not really a problem. This is a push about unread count status that is useful for the red badge on iOS
