### ISSUE TITLE
no unread message notification green circle

### ISSUE THREAD

**Issue by ikke-t** [element-hq/element-x-android#1407]
### Steps to reproduce

1. Where are you starting? What can you see?

I installed Android ElementX couple weeks ago. I see in DMs there is green bullet at the right end of dm row, but in room list no normal room shows this green bullet even if there are new messages. I see that from web element and old android element, which have the markif of unread messages.

Below image has unread message, green bullet missing:
![image](https://github.com/vector-im/element-x-android/assets/1146409/f3dc3ff2-7957-4ba5-9c0a-3b737fdce432)

3. What do you click?

I go to opening screen of elementX

#### What did you expect?

Channels should show unread messages with green circle at the right side.

#### What happened instead?

No green circle, except for the DMs.

### Your phone model

OnePlus 11

### Operating system version

Android 13

### Application version and app store

ElementX 0.2.0, latest one today from google store 2023-9-21

### Homeserver

hacklab.fi

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by spaetz** [comment]
Same, with current dendrite homeserver and current sliding sync. Element shows unread markers for rooms, ElementX does not. Happy to send logs if it helps.

**Comment by manuroe** [comment]
We revisited the logic of read receipts and unread state in the SDK in December and January. It was not working before. The behavior was quite random. It should be solid now.
