### ISSUE TITLE
Implement large emoji

### ISSUE THREAD

**Issue by nadonomy** [element-hq/element-x-android#1438]
### Your use case

![image](https://github.com/vector-im/element-x-android/assets/4626865/6d58ce1e-2c31-44dc-9e63-661794003fa9)

Left: Element X iOS. Right: Element X Android.

We should match the implementation here (& Element Web) where we enlarge emoji when sent on their own.

### Are you willing to provide a PR?

No

**Comment by amshakal** [comment]
This would be a nice to have.
