### ISSUE TITLE
Message not sent (composed without network)

### ISSUE THREAD

**Issue by toger5** [element-hq/element-x-android#1480]
### Steps to reproduce

1. Where are you starting? What can you see?
No network connection. In a PM room.
2. What do you click?
I type in two messages.
3. More steps…

#### What did you expect?
I expected them to be sent as soon as I do have network conenction.
#### What happened instead?
One of the messages got sent the other one got lost.

### Your phone model

s21 Ultra

### Operating system version

Android 13

### Application version and app store

Element X 0.2.4

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by manuroe** [comment]
We finished the send queue work at the beginning of summer 2024 in https://github.com/element-hq/element-internal/issues/312.
This use case is now managed.
