### ISSUE TITLE
Self verification doesn't work

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-android#1489]
### Steps to reproduce

"Cannot verify my session with Element Web, in Element X. Both sides let me initiate verification, but the other side never shows the pop-up to proceed - well, sometimes I see the verification request pop up for less than .5 seconds on web, before it disappears, and if I have a verification request initiated from Web and then try to initiate in X it closes the Web model saying the other end cancelled the request."

from `@john:matrix.freelock.com`

#### What did you expect?

self-verification should work

### Application version and app store

User-Agent: Element X/0.2.1 (Google Pixel 4a; Android 13; TQ3A.230805.001; Sdk TODO)

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jasper-at-windswept** [comment]
I'm having the same problem!

**Comment by manuroe** [comment]
The original issue should have been fixed now.

@jasper-at-windswept Element X cannot be used yet to verify another new login. This is known issue listed in https://github.com/element-hq/element-meta/issues/1915 as "No verification of a new login on another device"
