### ISSUE TITLE
Long pressing list points in messages with `<ol>` doesn't bring up context menu

### ISSUE THREAD

**Issue by rom4nik** [element-hq/element-x-android#1521]
### Steps to reproduce

1. Send a message using non-X Element Android (X uses `<p>` instead of `<li>` tags), or (likely) Element Desktop, or Nheko with a list, e.g.:
```
1. first
2. second
3. third
```
2. Ensure that `formatted_body` has `<ol>` tags, e.g.:
```
    "content": {
        "body": "1. first\n2. second\n3. third",
        "format": "org.matrix.custom.html",
        "formatted_body": "<ol>\n<li>first</li>\n<li>second</li>\n<li>third</li>\n</ol>",
        "msgtype": "m.text"
    },
```

#### What did you expect?
Menu appears.
#### What happened instead?
Similar to #1232:

https://github.com/vector-im/element-x-android/assets/46846000/66eef651-3089-4657-be7c-99535e69f0bc

The list with 4 points (first message) was sent with EXA, doesn't contain `<ol>` and has working long press. Source of that message:
```
    "content": {
        "body": "1. first\n2. second\n3. third\n4. fourth",
        "format": "org.matrix.custom.html",
        "formatted_body": "<p>1. first</p><p>2. second</p><p>3. third</p><p>4. fourth</p>",
        "msgtype": "m.text"
    },
```

### Your phone model

Google Pixel 3

### Operating system version

Android 12

### Application version and app store

096d575, debug build from GHA

### Homeserver

Synapse 1.93.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jonnyandrew** [comment]
This should be fixed by https://github.com/vector-im/element-x-android/issues/1433.

**Comment by rom4nik** [comment]
I've retested with https://github.com/element-hq/element-x-android/commit/1e86d8279beec0d035b04008ec7d3b3635b4135a on the same messages, it's fixed now, thanks!
