### ISSUE TITLE
Messages with `<ol>` and list items starting at index other than 1 are shown in bubble as starting at 1

### ISSUE THREAD

**Issue by rom4nik** [element-hq/element-x-android#1522]
### Steps to reproduce

1. Send the following message via a client that uses `<ol>` for messages with lists with multiple items (e.g. non-X Element Android, Nheko, likely Element Desktop):
```
2. second
3. third
```
2. Ensure `formatted_body` contains `<ol start=\"2\">`, e.g.:
```
    "content": {
        "body": "2. second\n3. third",
        "format": "org.matrix.custom.html",
        "formatted_body": "<ol start=\"2\">\n<li>second</li>\n<li>third</li>\n</ol>",
        "msgtype": "m.text"
    },
```

#### What did you expect?
Message bubble shows the message as intended.
#### What happened instead?
![Screenshot_20231010-000305_Element X dbg](https://github.com/vector-im/element-x-android/assets/46846000/3a71067a-c5dc-4f16-ab75-a32e24f5e36c)

In context menu:
![Screenshot_20231010-000309_Element X dbg](https://github.com/vector-im/element-x-android/assets/46846000/25dbe41a-2d90-4b77-a0af-ae0346cb7d74)

### Your phone model

Google Pixel 3

### Operating system version

Android 12

### Application version and app store

096d575, debug build from GHA

### Homeserver

Synapse 1.93.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
We will not fix this issue right now.
