### ISSUE TITLE
Attached image file is cropped in timeline preview

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-x-android#1584]
### Steps to reproduce

1. Send a vertical image in a room

#### What did you expect?
Image is not cropped, e.g. preview in timeline looks like this:
![1000005744](https://github.com/vector-im/element-x-android/assets/51663/9ffa246f-bfa6-4438-8c22-66adb3231b9a)

#### What happened instead?
The top and bottom of the screenshot is cropped in the timeline:
![1000005746](https://github.com/vector-im/element-x-android/assets/51663/4475b324-10d7-4727-8f7c-1a170644b616)

### Your phone model

Pixel 6a

### Operating system version

Graphene OS

### Application version and app store

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

Internal issue ID: AX-01

**Comment by rom4nik** [comment]
IIRC that was fixed some time ago, works for me now (4a8b82e0f3b94fa984663b62da4e6f18418358b4) with your first screenshot:

![Screenshot_20231229-233309_Element X dbg](https://github.com/element-hq/element-x-android/assets/46846000/bdf2f740-d510-4310-91a7-d862b32bf38c)

**Comment by bmarty** [comment]
Yes, it's now fixed. Thanks!
