### ISSUE TITLE
Loading spinner when selecting different options on the room notifications setting page

### ISSUE THREAD

**Issue by callumu** [element-hq/element-x-android#1647]
### Steps to reproduce

Room details page -> Notifications -> change any option

### Outcome

This should just be instant with no spinner or flickering

https://github.com/vector-im/element-x-android/assets/110109933/f92d4ff2-2702-400c-a06f-11e35d1d20dc

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by jmartinesp** [comment]
This is sending some requests to the homeserver, so it can't be instant. It can be quite fast though, and we might be able to debounce the spinner so it doesn't appear most of the time.

**Comment by kittykat** [comment]
@callumu would it work if we showed the spinner for a minimum amount of time so that it didn't flicker?
