### ISSUE TITLE
Room doesn't update even though notification shows new message

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#1811]
### Steps to reproduce

1. Notification shows new message
2. Klick on notifications leads to room

#### What did you expect?
See room with new message

#### What happened instead?
Room is completely empty at first

![Screenshot_20231115-112910](https://github.com/vector-im/element-x-android/assets/640121/fb8f6dab-825b-4a76-894a-f3e9a5740513)

Leaving room and going back in brings some messages, but not the latest that was notified

![Screenshot_20231115-112941](https://github.com/vector-im/element-x-android/assets/640121/fefc17f3-64ee-48e2-bb31-3d4c2db9322f)

### Your phone model

Pixel 5

### Operating system version

Android 14

### Application version and app store

0.3.2-nightly

### Homeserver

element.io

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
In the logs I can see several network connection errors around that time, but the sliding sync process tries to restart right ahead. I just tested a similar environment myself by disabling the WiFi connection in my test device and the timeline seems to recover and load the pending messages when the connections is restored.

**Comment by zopieux** [comment]
This behavior (unclear if bug or feature) is extremely frustrating. Notifications are, most of the time, my primary entry point to Element X. Every time I tap on one, the room displays but shows the previous state i.e. *without* the latest messages displayed in the notification, even though the are precisely why I tapped on it in the first place. A good 2-3s is necessary for the latest state to sync, which is excruciating in daily use.

This is 100% reproducible and that sync delay is relatively stable. This is in e2e encrypted rooms it case it matters.

**Comment by jmartinesp** [comment]
If we're just talking about the contents of the timeline being out of date, sadly this is expected at the moment. In the previous Element Android app we did a full sync when a notification arrived, which got the app always up to date, but could take a while to finish, and would delay the notifications for that amount of time. In EX we just retrieve the event and displaying the notification is almost instant, but we now need to do a sync when we open the actual timeline to make sure we're up to date.

In the future there should be a way to both read the notification content and perform opportunistic syncs when a notification arrives, but the SDK can't handle both at the same time at the moment if I'm not mistaken.

**Comment by zopieux** [comment]
>In EX we just retrieve the event and displaying the notification is almost instant, but we now need to do a sync when we open the actual timeline to make sure we're up to date.

Thanks for the quick reply. That makes sense and seems to match the behavior I'm describing. Good to know an improvement is already planned – if you have a FR track for that, do link it so I can +1 :-)

**Comment by zopieux** [comment]
>There is nothing we can do at the app level to improve this.

Nothing that can be done *now*, as it is blocked on a SDK feature. Nevertheless, the regressive behavior is still present. I am grateful for the awesome work done by the contributors, and I understand that many projects [prefer to keep a small number of open GitHub issues](https://nostalebots.xyz/). However, please be considerate of the time spent by beta-users filing properly-formed bug reports, especially when they are confirmed and can be addressed in the future, per the rough action plan outlined in the [comment you linked to](https://github.com/element-hq/element-x-android/issues/1811#issuecomment-1931487790).

I wish GitHub had better support for bug dependencies to avoid /dev/null'ing blocked bugs.

**Comment by kongo09** [comment]
I'd like to suggest to keep this open as it is not resolved and there is an ambition to fix it.

That the solution is in the SDK is a technical fact that from a user perspective is not relevant. I'd prefer we take the user perspective here.
