### ISSUE TITLE
Scroll to end of timeline when sending a new message

### ISSUE THREAD

**Issue by ganfra** [element-hq/element-x-android#1877]
As a user that has send a message I want the timeline to scroll to that message at the end of the timeline so that I can have a look at what I just send.

**Comment by rom4nik** [comment]
If I may chime in, this sounds like it would make reading message backlogs and sending replies as I'm reading much more inconvenient, unless there's a reliable "back to last unread" feature coming too, to quickly jump back to where I was right before that automatic scroll.

**Comment by Aquathing** [comment]
> unless there's a reliable "back to last (un)read" feature coming too

I think you can (or, rather, will be able to) click on the message you replied to in order to go back up.

**Comment by VolkerJunginger** [comment]
Only working for text-messages. Should have the same behaviour w. any message.

**Comment by bmarty** [comment]
> Only working for text-messages. Should have the same behaviour w. any message.

It's not working for images for instance since there is no local echo support when sending images right now on the SDK.
So it's linked to https://github.com/matrix-org/matrix-rust-sdk/issues/1732

**Comment by VolkerJunginger** [comment]
Can't you just scroll down when the message has been send?

**Comment by ganfra** [comment]
This sounds like a bad idea for a media which can take time to get back from sync. And scrolling to the bottom as soon as we hit the send button is not great neither to me. So not sure what we can do on this for now.

**Comment by bmarty** [comment]
The app could also move to the bottom of the timeline as soon as there is a new message sent by the user (with the side effect that it will scroll even if the user has sent the message from another session - which could be declared "acceptable" I think).

**Comment by manuroe** [comment]
EIX uses the stick at bottom even for incoming messages

**Comment by manuroe** [comment]
@VolkerJunginger will come back to the solution we should use on both platforms.

**Comment by bmarty** [comment]
I have tested what's the behavior on WhatsApp:
- WhatsApp mobile: scroll to the history
- send a message from WhatsApp Desktop (same account)
The timeline is scrolling to live on WhatsApp mobile.

This is the same if you do it with exchange the 2 WhatsApp clients.

I guess we can do the same on Element then, but I let @VolkerJunginger confirm this.

**Comment by VolkerJunginger** [comment]
The WhatsApp behaviour is the same we did on iOS, right? If so lets go with this for now.

**Comment by ganfra** [comment]
Not sure this is exactly what is done on iOS. @pixlwave do you if it automatically scrolls if you receive a message you sent from another session?

**Comment by pixlwave** [comment]
Yep @ganfra is correct, we don't scroll for the user's other sessions. We basically send a signal to [scroll to bottom](https://github.com/element-hq/element-x-ios/blob/669141b1193fd2cde06b24fe77ca5c1673dc12ef/ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift#L306-L312) whenever the app queues a [message](https://github.com/element-hq/element-x-ios/blob/669141b1193fd2cde06b24fe77ca5c1673dc12ef/ElementX/Sources/Services/Timeline/TimelineProxy.swift#L347) or finished sending some form of [media](https://github.com/element-hq/element-x-ios/blob/669141b1193fd2cde06b24fe77ca5c1673dc12ef/ElementX/Sources/Services/Timeline/TimelineProxy.swift#L240).

**Comment by bmarty** [comment]
For posterity, I discover now that it's a setting on Element Web:

<img width="1031" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/fc8636fd-89d8-47e9-94c9-b16ee5779b8e">
