### ISSUE TITLE
Extra new lines

### ISSUE THREAD

**Issue by cyberb** [element-hq/element-x-android#1896]
### Steps to reproduce

I have observed this issue on mesages coming from telegram bridge, not sure about the scope of it.

### Outcome

Messages from telegram (possibly other bridges) have extra new lines. It is ok in the old Element app.

![IMG_20231127_092012](https://github.com/vector-im/element-x-android/assets/885528/2f65507e-8d0f-44da-8346-3d35580b5d54)

![IMG_20231127_092028](https://github.com/vector-im/element-x-android/assets/885528/8f991c7d-1a78-4767-8f7d-b25c411a522a)

Similar issue with links

![IMG_20231127_092802](https://github.com/vector-im/element-x-android/assets/885528/51423fe4-3ee4-4de5-9464-4025bf72dea8)
![IMG_20231127_092833](https://github.com/vector-im/element-x-android/assets/885528/bd93d1f0-f8f1-4bed-8bef-f97c10dbcdb0)

Telegram bridge devs think it is ElementX problem, I have no reason to not beleive them: https://github.com/mautrix/telegram/issues/944

### Your phone model

Redmi 9

### Operating system version

Android 10

### Application version and app store

0.3.1

### Homeserver

Dendrite

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Hello @cyberb, thanks for reporting. Do you still observe the issue using the latest version of the application?

**Comment by cyberb** [comment]
Right, v0.4.5 does not have this problem anymore, thanks!
