### ISSUE TITLE
Remove flag for read receipt.

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#1900]
RR should be live now, so we can remove the feature flag (which was used as a lab flag) and make the feature available to everyone.

**Comment by bmarty** [comment]
Waiting for https://github.com/matrix-org/matrix-rust-sdk/issues/2889

**Comment by claell** [comment]
The mentioned blocking issue is closed. Is this issue even still relevant?

**Comment by bmarty** [comment]
Yes, I'll double check that the issue is gone, and will remove this flag. Note that the feature is now enabled by default.

**Comment by claell** [comment]
Perfect! Yup, saw the enablement of the feature. 🙂
