### ISSUE TITLE
Persistent green dot when using EC

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-x-android#1901]
### Steps to reproduce

1. Do a call with EX iOS (call triggered from iOS)
2. Both parties leave call
3. See green dot in the room list for the DM

#### What did you expect?
Room is not marked as unread
If the room is marked as unread, then going to the room clears the marker

#### What happened instead?
Stuck green dot

### Your phone model

Pixel 6a

### Operating system version

Graphene OS

### Application version and app store

Nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
I do not repro the issue. The call picto is correctly vanishing once the call is over.
