### ISSUE TITLE
Timeline loading scroll glitch

### ISSUE THREAD

**Issue by ghost** [element-hq/element-x-android#1948]
### Steps to reproduce

When you scroll through the chat history and previous messages load, it is not possible to continue scrolling until you a bit scroll back the chat.
Even if the messages have already been loaded.

https://github.com/vector-im/element-x-android/assets/115932548/a806ada4-f580-4394-89f3-15669d7551fa

#### What did you expect?
To be able to scroll through the chat.

#### What happened instead?
The timeline was blocked somehow

### Operating system version

Android 14

### Application version and app store

0.3.2 (40003020) GitHub universal APK release

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by manuroe** [comment]
Can you check on the coming version (0.4.2)?
