### ISSUE TITLE
Add support for rendering `m.sticker` Event.

### ISSUE THREAD

**Issue by d4f5409d** [element-hq/element-x-android#1949]
![Screenshot_2023-12-03-09-29-18-82_508fb70dcdbd51b3b84edd38d0498869.jpg](https://github.com/vector-im/element-x-android/assets/76624594/6658304a-0cac-4e3f-b8d9-4c2b8aa71d61)

`{"content":{"body":"\ud83e\udd14 (thinking face)","external_url":"https://t.me/organicmaps/34029","fi.mau.telegram.source":{"chat_id":1495267990,"id":34029,"peer_type":"channel","space":1495267990},"info":{"fi.mau.telegram.sticker":{"alt":"\ud83e\udd14","id":"1067584434330402952","pack":{"access_hash":"1356583802377053769","id":"1067584434330402819"}},"h":256,"mimetype":"image/webp","size":26924,"thumbnail_info":{"fi.mau.telegram.sticker":{"alt":"\ud83e\udd14","id":"1067584434330402952","pack":{"access_hash":"1356583802377053769","id":"1067584434330402819"}},"h":256,"mimetype":"image/webp","size":26924,"w":256},"thumbnail_url":"mxc://t2bot.io/b3bd9bc62375efe07a0cb0c5ba3a51aeb0369fdf1730481839837020160","w":256},"url":"mxc://t2bot.io/b3bd9bc62375efe07a0cb0c5ba3a51aeb0369fdf1730481839837020160"},"origin_server_ts":1701413995000,"room_id":"!wqHDOeaqKhfWGKYfGs:matrix.org","sender":"@telegram_5718178991:t2bot.io","type":"m.sticker","unsigned":{},"event_id":"$jKXU4ymDyFJhbLEZ0lNpV4KPRpMLkuZfxVgN72FT5XY","user_id":"@telegram_5718178991:t2bot.io"}`

**Comment by bmarty** [comment]
Yes, `"m.sticker"` type is not supported. Not a priority though (just to let you know).

**Comment by d4f5409d** [comment]
I know I have just let you know this exists not to be forgotten about

**Comment by surakin** [comment]
Hi! I decided to give this a shot because these unsupported events were bothering me :smile:
