### ISSUE TITLE
have quick reply on notifs that when you reply via the notif it replies to the message in the room

### ISSUE THREAD

**Issue by ninchuka** [element-hq/element-x-android#1966]
#### What would you like to do?
when you reply to a notification of a message it replies to the message in element x
#### Why would you like to do it?
its nice to quickly reply to a message without opening the app and possible getting sidetracked by other rooms or conversations
#### How would you like to achieve it?
have a quick reply option when a notification gets sent like in ele android, that replies to the message in the notification, which isnt how ele android does it currently

### Have you considered any alternatives?

you could just send the message while not replying but that can easily cause confusion in a busy room

### Are you willing to provide a PR?

No

**Comment by Git-North** [comment]
Would be great

**Comment by Xiretza** [comment]
See also #1547
