### ISSUE TITLE
Sharing Support 

### ISSUE THREAD

**Issue by DoM1niC** [element-hq/element-x-android#1980]
#### What would you like to do?
Share Media like a Picture to Element X -> Room / DM

#### Why would you like to do it?
Easier to send files 
### Are you willing to provide a PR?

Yes

**Comment by anytimesoon** [comment]
That's one of the main features of a chat app. Sharing links and pictures and things. Would be great to have it implemented!

**Comment by fbruetting** [comment]
Is it maybe possible to bump the priority of this issue a bit? It’s one of the core features we need with the high media traffic people nowadays are accustomed to. Having both apps installed is annoying, and having just Element-X is cumbersome with having to save everything and then manually select for forwarding. :/

**Comment by anytimesoon** [comment]
Couldn't agree more. I'm surprised to see this has been labeled as a nice to have

**Comment by fbruetting** [comment]
Thank you very much!! 😊

**Comment by fbruetting** [comment]
Sadly, videos don't work. The spinner first runs like endlessly, then the error "failed to handle incoming share request" appears. Tested via sharing from WhatsApp.
