### ISSUE TITLE
Improve description of advanced settings

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#1987]
#### What would you like to do?
Current description text of the two advanced settings is confusing and not "symmetric".
- _Rich-Text-Editor_ talks about the option to deactivate it, to achieve something else (enter Markdown). That's counter intuitive. Normally, settings are used to activate the thing that's described.
- _Show Source_ uses at least in the German translation wording, that I cannot understand what it means

#### Why would you like to do it?
Settings should be intuitive. If not, the explanation should be short, precise and clear to help.

#### How would you like to achieve it?
For the RTE, either make it a choice between RTE or Markdown, or adapt the wording to be positive and active, e.g.:
> Activate the RTE for advanced visual editing and formatting of messages. With RTE deactivated, you can still create formatted messages using Markdown with plain text.

For the Show Sources option, I don't have a suggestion as I don't understand what it is supposed to do.

### Additional context

![image](https://github.com/vector-im/element-x-android/assets/640121/003ca943-bce5-4381-bb74-fb064f1a4fa2)

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
(@kongo09 if possible, before taking screenshots of the application, can you set your phone language into English please?)

**Comment by bmarty** [comment]
Changing wording to `View source` was a request from @kittykat to align with the iOS app https://github.com/vector-im/element-x-android/issues/1868.

Happy to revert to `Developer mode`, but it was maybe not clear enough what it means.

FTR discussion also occurred [here](https://github.com/vector-im/element-meta/issues/2042#issuecomment-1739476560)

**Comment by kongo09** [comment]
So #1868 doesn't make it any clearer. It just argues for consistency, which in itself is great.

Experimenting with it, I now found that it enables a context action to view the source of a message. Now that very clearly is nothing for an ordinary user. I don't think this setting belongs here, but it should be part of the Developer Settings (or Options, as they're inconsistently called). Moving it over would solve this part of this issue for me.

**Comment by kongo09** [comment]
I noticed that Google has a similar challenge in its native keyboard settings:


https://github.com/element-hq/element-x-android/assets/640121/231fd8de-8fda-4f2e-bd2c-125b1aaf2642


The two settings play with each other. You enable one and the other automatically disables. That makes it very simple and explicit.

**Comment by bmarty** [comment]
Sorry, I do not see the point of your latest comment in the context of this particular issue. The 2 toggles in Advanced Settings screen are for 2 distinct things, or am I missing something?

**Comment by kongo09** [comment]
It's a similar case.

- As a user, I might want to enable RTE as I have no clue about any other formatting options. 
- As a user, I want to enable Markdown as I can quickly type my desired text formatting

This could end up as two toggles:

**Show Rich-Text-Editor**
Show an editor in the message input field that allows visual editing of the message text. When turned on, this disables Markdown.

**Enable Markdown editing**
Allow Markdown in the message input field for enter text formatting as markup. When turned on, this disables the Rich-Text-Editor.

Enabling the first would disable the second and the other way around.

**Comment by bmarty** [comment]
OK, I see, thanks for clarifying.

**Comment by manuroe** [comment]
@VolkerJunginger Can you look at this and prioritise it, please?

If we decide to do it, we need to synchronise to make it happen on iOS too.

**Comment by bmarty** [comment]
Closing as stale issue, also the Rich Text Editor setting does not exist anymore.
