### ISSUE TITLE
User avatar are not always displayed in notification

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#1991]
Sometimes the letter is used instead.

Also the notifications are not rendering images, as it was the case on Element Android.

**Comment by rom4nik** [comment]
I'm on GHA debug build of 0a16af1d4ffc8911b949eb8c696f75dbbbe4f2c5, and it seems that if app is in recents, then the avatar images appear in notifications. If the app has been removed from recents, the images don't appear, even in subsequent notifications, and even after removing the first notification and receiving new notification for new messages from the same sender. Tested it a handful of times, occurs consistently on my device (Pixel 3, Android 13).

**Comment by bmarty** [comment]
You're right @rom4nik , let's re-open this with this useful intel.
