### ISSUE TITLE
Permanent "Your keys are still being backed up" on logout

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-x-android#2008]
<img width="302" alt="image" src="https://github.com/element-hq/element-x-android/assets/9841565/53b17922-23e5-4927-afdf-7fa1c193d5dc">

it's 24/24 but not changing

**Comment by bmarty** [comment]
Not 💯 sure, but I think the app will not get `Done` in this case. So we should consider that `Uploading` state with `backedUpCount == totalCount` is the same than `Done` state.
