### ISSUE TITLE
Pills: improve pills rendering with long content

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#2026]
Send a room alias to a public room to a room, for instance, type `#element-x-android:matrix.org` from a web client

Observe the rendering on Element X Android: the pills is truncated:

<img width="348" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/b198016d-85ca-4be5-8a37-cbd2591bbc5e">

Originally I though that the pills text was not correctly parsed, but actually, when in landscape, we can see the the pills is correctly rendered:

<img width="797" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/80fdc980-6624-4e7e-a936-2c2cfca8e75b">

It's maybe possible to use some ellipsis?

Also, as a side note, Element Web is resolving the room data and is displaying this:

<img width="250" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/623e55a8-e86b-4ff5-9ea5-094184bf03a1">

We may want to resolve the room name at some point. Note sure for the room avatar since we want to reduce the number of avatars (we use `@` for user mention instead of avatar, but does this applies to rooms?).

**Comment by jmartinesp** [comment]
My bad. A truncation/ellipsis at 20 chars should have been added, but I completely forgot about it.

**Comment by manuroe** [comment]
Seems done now.
