### ISSUE TITLE
Always show user pic in message action sheet

### ISSUE THREAD

**Issue by VolkerJunginger** [element-hq/element-x-android#2032]
### Steps to reproduce

When opening the message action sheet (long-press any massage type) either a preview of the message or the message type icon is show.

We alway want to show the senders avatar (see iOS)
![image](https://github.com/element-hq/element-x-android/assets/118339066/b707c62a-50d4-4c4e-9141-b1ac0c0cc0b1)

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by VolkerJunginger** [comment]
Will be fixed w. https://github.com/element-hq/element-x-android/issues/2032
Not sure if in 2023. But Q1-2024

**Comment by bmarty** [comment]
On iOS, for an image for instance:

<img width="397" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/f6a8cd4b-a364-4d78-892a-c04e353d04a4">

@VolkerJunginger do you want us to add the user avatar and keep the thumbnail, or replace the thumbnail?

I would prefer to keep the thumbnail, but your choice.

**Comment by VolkerJunginger** [comment]
Please replace the thumbnail w. the user-avatar. Thanks!
