### ISSUE TITLE
Magnify Room avatar

### ISSUE THREAD

**Issue by VolkerJunginger** [element-hq/element-x-android#2033]
### Your use case

Please also enable to magnify the room avatar (same story as https://github.com/element-hq/element-meta/issues/2208) but also for group-chats

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
Thanks, done and merged before you create the issue in https://github.com/element-hq/element-x-android/pull/2027 :). You will be able to test it in tomorrow's nightly.

**Comment by VolkerJunginger** [comment]
works! Thanks!
