### ISSUE TITLE
Latest release shows dev options independently of the "developer mode" toggle

### ISSUE THREAD

**Issue by bnjbvr** [element-hq/element-x-android#2056]
### Steps to reproduce

Download latest release of ElementX Android on google play.

### Outcome

Developer options are always shown, although I haven't toggled on the "developer mode" option in the advanced settings. In fact, it's always shown, whether the toggle is on or off.

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Are you sure the version you're using is coming from the PlayStore?

`Developer options` are shown on `Debug` and `Nightly` builds, not `Release` builds as per [this code](https://github.com/element-hq/element-x-android/blob/main/features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/root/PreferencesRootPresenter.kt#L95), there is not link with `Advanced settings` / `Developer mode` (which has been renamed to `View source`) switch.

I have checked with the version from the PlayStore and `Developer options` is not shown.

**Comment by bnjbvr** [comment]
Oops you're right, my bad it's a nightly, and quite an old one.
