### ISSUE TITLE
Empty state when the user has no room

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#2057]
- Create an account and do not join any room with another client
- Connect on this account with Element X

There is no empty state, the room list is displaying placeholders forever

<img width="424" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/fc36f7f1-1264-4542-8a1c-c226d96d7733">

**Comment by frebib** [comment]
Sounds related to https://github.com/matrix-org/matrix-rust-sdk/issues/2844

**Comment by bmarty** [comment]
Closed in favor of #2330
