### ISSUE TITLE
Edited bubble broken

### ISSUE THREAD

**Issue by VolkerJunginger** [element-hq/element-x-android#2060]
### Steps to reproduce

Create a text message. Edit it. You'll see that the "Edited" hint & the text overlaps.

While testing it last week (cw50) worked already in an older build.

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
@VolkerJunginger I cannot repro, but maybe not searching in the right direction. Can you attach a screenshot to the issue please?

**Comment by VolkerJunginger** [comment]
![image-20231219-122606](https://github.com/element-hq/element-x-android/assets/118339066/dc2c1f49-4e6c-4169-bcc0-e9ba3a367e22)

**Comment by VolkerJunginger** [comment]
see 2nd and third message.

**Comment by jmartinesp** [comment]
The way how this works was slightly changed when we replaced the rendering of text timeline messages and added mentions, but maybe it was enough to break this.

**Comment by bmarty** [comment]
(maybe due to the German word for `edited` which is longer, but I think we [measure](https://github.com/element-hq/element-x-android/blob/main/features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/timeline/components/event/ExtraPadding.kt#L51) the translated word)

**Comment by jmartinesp** [comment]
Technically, the best solution would be to edit the RTE library to be able to have an `onTextLayout` callback and use something like [this](https://github.com/SmartToolFactory/Jetpack-Compose-Tutorials/blob/master/Tutorial1-1Basics/src/main/java/com/smarttoolfactory/tutorial1_1basics/chapter3_layout/chat/widget/ChatFlexBoxLayout.kt#L116), but in the meanwhile I'll add a fix for the current 'add NBSP chars' solution.

**Comment by VolkerJunginger** [comment]
bug is still there w. nightly from 21.12.

**Comment by jmartinesp** [comment]
It seems to work fine for me in German in the last nightly:

<details>
<summary>Screenshot</summary>
<img src='https://github.com/element-hq/element-x-android/assets/480955/db5dd43b-0b59-4dfe-a13b-7341068db342' />
</details>

Can you share an example of a case where it doesn't work?

**Comment by manuroe** [comment]
@VolkerJunginger can you check it again?

**Comment by VolkerJunginger** [comment]
![Screenshot_20240122-090058](https://github.com/element-hq/element-x-android/assets/118339066/6c1fd5eb-82a1-4ddb-8b59-023ed6d9ab27)

It is still broken.

**Comment by jmartinesp** [comment]
Not for me:

<img width="332" alt="image" src="https://github.com/element-hq/element-x-android/assets/480955/e86a27c9-9d01-4274-b78a-255d253967b3"> 

There may be some corner case that causes the issue, but we haven't seen it anywhere else, so I don't think that's the case. 

Are you sure you're using the latest version?
