### ISSUE TITLE
Emojis in the bottom sheet are very tiny

### ISSUE THREAD

**Issue by amshakal** [element-hq/element-x-android#2066]
### Steps to reproduce

Go to a room and long press a message bubble, a bottom sheet will pop up, select add a reaction -> a new bottom sheet is pop up

### Outcome

The emojis should be be 5 in a row, not 7. The current tapping area is smaller than expected.

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by jmartinesp** [comment]
> The emojis should be be 5 in a row, not 7.

Just to clarify: we're talking about what should appear in vertical orientation in the most commonly used resolution, not always using 5 items in a row, right? That could end up in weird situations like this one, where the emojis are gigantic:

<img width="452" alt="image" src="https://github.com/element-hq/element-x-android/assets/480955/a35bb083-ece2-4937-94f6-7594887d94c0">

**Comment by frebib** [comment]
The old (current master) behaviour seems to make more sense to me. Enforcing a number of columns is not a good way to go when you consider that different people have different display scaling settings. For me, there were 9 columns before as I run quite a small scale.
Can we stick with the old behaviour, but just increase the emoji size?

**Comment by jmartinesp** [comment]
@amshakal just pinging you in case you didn't see the mention above (it was added on when editing the message, so maybe there was no notification). Taken the results in #2074 and the input from @bmarty and users as @frebib, do you think we should set a fixed column count, or is it ok with just increasing the emoji size as is done in that PR?

**Comment by amshakal** [comment]
Hey I think increasing the size makes more sense, given the discussion, I forget we dont have control over all phono sizes. Im happy with #2074. Thanks
