### ISSUE TITLE
Reactions are offset too far right in DM chats

### ISSUE THREAD

**Issue by frebib** [element-hq/element-x-android#2076]
This is a regression from https://github.com/element-hq/element-x-android/pull/1981

### Steps to reproduce

- Add a reaction to a message in a message *received* in a DM chat (on the left of the timeline)
- Notice that it's a bit further right than it should be

#### What did you expect?
Reactions to be offset from the left of the bubble by the same amount as in non-DM chats

#### What happened instead?
They're too far right

### Your phone model

Pixel 8

### Operating system version

Android 14

### Application version and app store

bd53b9c5b990e5ecbfe4856dac1ae55840a4bf97

### Homeserver

Synapse develop

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks for reporting! I am taking the point. The problem can be seen in this screenshot:
https://github.com/element-hq/element-x-android/blob/develop/tests/uitests/src/test/snapshots/images/ui_S_t[f.messages.impl.timeline.components_TimelineItemEventRowForDirectRoom_null_TimelineItemEventRowForDirectRoom-Day-17_17_null,NEXUS_5,1.0,en].png
