### ISSUE TITLE
Text modifications made by android keyboard seem to be ignored

### ISSUE THREAD

**Issue by K4LCIFER** [element-hq/element-x-android#2081]
### Steps to reproduce

An example of this would be the following:
1. Enable the default android keyboard
2. Type `test` in Element X
3. Double tap spacebar to place a period
4. after the period was placed, type some more text, and observe that the period gets removed.

I've observerd similar behaviour with the autocorrect suggestions. If you tap on a word, then tap on the suggestion, then type text, the suggestion gets reverted back to the previous text.

#### What did you expect?

I would expect that I would be able to use the text shortcuts/modifications that my keyboard provides.

#### What happened instead?

Any text shortcuts/modifications made by the keyboard get ignored/replaced by Element X.

### Your phone model

Google Pixel 6

### Operating system version

Android 14

### Application version and app store

0.3.2

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
This was fixed in https://github.com/matrix-org/matrix-rich-text-editor/pull/902 and it's already in the nightlies, but the bugfix hasn't reached the stable versions yet. There should be a new stable release soon with this bugfix included, sorry for the inconvenience until then.
