### ISSUE TITLE
The keyboard cannot be opened in the room search

### ISSUE THREAD

**Issue by frebib** [element-hq/element-x-android#2082]
When in room search, if the keyboard is closed for any reason there's no way to re-open it. Normally the way you'd do that is click (again) on the text box to open it, or click off the input box to deselect it then click on it again to open the keyboard.

Steps to reproduce:
- open room search
- hit the back button to close the keyboard
- realise theres no way to re-open the keyboard

**Comment by bmarty** [comment]
I can repro and I observe the same issue in the search member screen from the room member screen. Quickly testing a SearchBar in a sample app and it's working as expected, so there is an issue on our side.

**Comment by bmarty** [comment]
The issue seems to be fixed now (testing on 0.4.6). Feel free to re-open if you still observe the issue.
