### ISSUE TITLE
Room transition animation happens twice since #2059

### ISSUE THREAD

**Issue by frebib** [element-hq/element-x-android#2084]
### Steps to reproduce

1. Open a room from the room list
2. Observe that the app now transitions once to the "unloaded room" and again to the "loaded room"

It's mostly visible on slower devices (my phone is new so is pretty quick, but enabling battery saver emulates it a little)

#### What did you expect?
The previous behaviour. Reverting #2059 goes back to the old/expected behaviour.
Specifically, it seems that the issue is that there is a transition from the "unloaded timeline" to the "loaded timeline" whereas before it didn't do that. 

#### What happened instead?
Here's a video I tried to capture of it happening. It's most visible in the last room opened

https://github.com/element-hq/element-x-android/assets/480955/871bf8b6-fab2-4865-ba5c-db422f91c5bc

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
I uploaded the video here in slow motion so it's a bit easier to see the issue. For whoever fixes this: take a look at the top app bar.
