### ISSUE TITLE
Rooms with default notification settings have green dot for all unread msgs despite no unread notifications

### ISSUE THREAD

**Issue by rom4nik** [element-hq/element-x-android#2090]
### Steps to reproduce

1. Have default notification rules set to notify in group rooms only on mentions and keywords:
![Screenshot_20231222-004244_Element X dbg](https://github.com/element-hq/element-x-android/assets/46846000/4fd8ac5d-d69b-47f7-a76d-6ced23571df4)

2. Have most group rooms use default notification rules, but some use custom rules also notifying only on mentions and keywords:
![Screenshot_20231222-004431_Element X dbg](https://github.com/element-hq/element-x-android/assets/46846000/961a4e96-9090-4b00-a1f6-bfd86f3fa196)

3. Go to room list

#### What did you expect?
Groups rooms where I have unread msgs but no unread notifications from mentions or keywords are shown with gray dot, like `Settings = Mentions, Activity = Yes, Mentions = No` in https://github.com/element-hq/element-x-android/issues/2079, no matter if they're using default notification settings or custom. 

#### What happened instead?
![Screenshot_202312.21-214623_Element X dbg](https://github.com/element-hq/element-x-android/assets/46846000/226a2631-538a-4244-9156-e85481580ea3)

`Mautrix-Signal Bridge` is using defaults; `TWIM offtopic continuation` is using custom notification settings, set to mentions and keywords. This issue wasn't present on a build from a few days ago, probably before https://github.com/element-hq/element-x-android/pull/2080. 

### Your phone model

Google Pixel 3

### Operating system version

Android 13

### Application version and app store

deff2d8fc5841f9538e77da9fce486db8f67671f, GHA debug build

### Homeserver

Synapse 1.98.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by frebib** [comment]
Related to https://github.com/matrix-org/matrix-rust-sdk/pull/2975 ?

**Comment by rom4nik** [comment]
For the record, this issue is back after merge of #2265.


https://github.com/element-hq/element-x-android/assets/46846000/ca861a27-3734-45dd-a568-36361ae69168

**Comment by jmartinesp** [comment]
That's a side-effect of that PR and the underlying Rust SDK logic. Opening those rooms should reset the value and it should behave better, although we've observed some other issues in our implementation.

**Comment by rom4nik** [comment]
No longer occurs on ede1dc0fabef597c46fd261ca20eaa7e58c3e47f, probably fixed by #2293.
