### ISSUE TITLE
Element Android 1.6.8 on F-Droid?

### ISSUE THREAD

**Issue by opusforlife2** [element-hq/element-x-android#2106]
### Your use case

Opening this issue because it seems like everyone has turned off notifications for the element-android repo. If there's nothing blocking 1.6.8 from being released on F-Droid, could you please let the F-Droid team know? It contains a critical fix for calling functionality that's been plaguing users for months.

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Yes, sorry, we did not do proper full release of EA recently. Next release 1.6.10 will be complete (SDK/App/F-Droid/Sample app), and is planned mi-January 2024.

**Comment by licaon-kter** [comment]
@bmarty you're joking right? You've released it to `1M+` users on Play but it's not ready for F-Droid and needs to be postponed for 2 months?!

**Comment by fuu0** [comment]
1.6.10 is also not released on FDroid. What is it? Do you want to push people to Google? Or don't you give a fuck about it because it doesn't affect you?

**Comment by licaon-kter** [comment]
@fuu0 will come soon https://gitlab.com/fdroid/fdroiddata/-/commit/0ec12b3bb5517d0b439bab330c43b9aff89f35be
