### ISSUE TITLE
Message content can be shown incomplete until scrolled off-screen and back

### ISSUE THREAD

**Issue by rom4nik** [element-hq/element-x-android#2155]
### Steps to reproduce

1. Have some kind of message in room (I'm not sure of specifics yet, see video below)
2. Notice that the message appears shorter than a few seconds ago
3. Scroll it off-screen and back

#### What did you expect?
Message is shown in its entirety at all times.
#### What happened instead?

https://github.com/element-hq/element-x-android/assets/46846000/6dfb3c18-fc13-44c3-b08e-c42327c4c5e3

For some reason it's this glitch happens somewhat repeatedly on this particular message. Rageshake sent before recording this video, after another occurrence on the same message, where the message was initially showing `da`, then after scrolling up and down once it showed full content, then after a few more scrolls it showed `da. a jak wysyłasz`, then after a scroll it showed full message again.

I don't think I've ever seen this on 87c8bc133f0b6190533e25a611e4b2e304156010 (previous version I've used) or older builds.

### Your phone model

Google Pixel 3

### Operating system version

Android 13

### Application version and app store

4f6c7421bd2daa6788e81da84691caa13b765594, GHA debug build

### Homeserver

Synapse 1.98.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by rom4nik** [comment]
A couple more recordings:

https://github.com/element-hq/element-x-android/assets/46846000/15326bca-9f75-4966-9501-69b2495df2ab

Additionally, in video above, when the full message is shown the text overlaps the timestamp.

https://github.com/element-hq/element-x-android/assets/46846000/52fb275d-a795-4754-8841-90cdaa54b099

Timestamps for video above:
1. 12s - full message appears after full scroll off-screen
2. 12-29s - scrolling and opening an image a few times, message still shown in full
3. 29-32s - scrolling and opening an image once, scrolling down has a bit of stutter, message now shows only first word again
4. 34-39s - scrolling and opening an image a few times, message still shown in full


https://github.com/element-hq/element-x-android/assets/46846000/d906abfb-f546-4526-995b-5acd34dd2739

And in video above the message is shown in full, but the timestamp first appears in correct place (extending the bubble a bit), but after a scroll off-screen and back, it's overlapped by text - similar to first video in this comment.

So far it looks like this stuff happens only on messages which are replies.

**Comment by frebib** [comment]
I've not been able to reproduce the strange words-disappearing bug but I do have a few more instances of timestamps overlapping the message. It feels like a bounds calculation race to me
![Screenshot_20240104-173235~2.png](https://github.com/element-hq/element-x-android/assets/775104/5e620013-38c6-447e-9510-1e94ace901b9)

![Screenshot_20240104-173614~2.png](https://github.com/element-hq/element-x-android/assets/775104/2b36f438-fa09-4468-a10d-ae42d83d4596)

**Comment by bmarty** [comment]
Yes, it may come from `ContentAvoidingLayout`. We may want to fix this before the next release.
