### ISSUE TITLE
Sticker forwarding doesn't work

### ISSUE THREAD

**Issue by surakin** [element-hq/element-x-android#2161]
### Steps to reproduce

Try forwarding a sticker and it will throw an error dialog that reads 'Error'

This seems to happen because only events of type Message can be forwarded and the Rust SDK has its own Sticker type

#### What did you expect?
Stickers forwarding should work
#### What happened instead?
It shows an error dialog saying 'Error'

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
Closing, as it's not possible anymore to forward a sticker. Feel free to add a dedicated issue to properly handle sticker forwarding.
