### ISSUE TITLE
Gboard auto correct reverts choice on next keypress

### ISSUE THREAD

**Issue by lasse-aagren** [element-hq/element-x-android#2168]
### Steps to reproduce

1. On a Pixel 7 Pro with all the latest upgrades, using stock Gboard as input source
2. When writing and mistyping a word, then choosing one of the suggested auto corrections
3. Word is now auto corrected on screen
4. And then continuing to write after the auto correct

#### What did you expect? 
I expected to see a sentence with the autocompleted word

#### What happened instead? 
I see a sentence with the word as it was mistyped before

See [video](https://photos.google.com/share/AF1QipPmMEjlEp3TCYOCOeJ3DmXUaG4dVGCVQf81CWjz0Xeaf4U-G0mUVR-OrtCVvIWr0Q?key=dnBZaEpOY2FvNG9uaWc5amFQY3pULTEtTHo3VjF3)

### Your phone model

Google Pixel 7 Pro

### Operating system version

Android 14, Security Update December 5th

### Application version and app store

Element X 0.3.2

### Homeserver

matrix-synapse-py3 1.98.0+bullseye1

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
I believe this has been fixed recently. Can you try again with the latest version of Element X, 0.4.0?

**Comment by lasse-aagren** [comment]
Is it in the play store? I'm a beta tester there, but don't seem to get it? If not,  I'll sideload it.

**Comment by lasse-aagren** [comment]
confirmed, version 0.4.0 fixes the issue. Closing this ticket.

Thanks for the info!
