### ISSUE TITLE
Text composer is removing carriage returns 

### ISSUE THREAD

**Issue by spongythecake** [element-hq/element-x-android#2170]
When composing a regular message, individuals often organize their conversations by creating paragraphs for new thoughts.

Video included 

https://github.com/element-hq/element-x-android/assets/146408892/9cd16424-abea-44ef-bee9-cb71ce01d806
**What I expect:**
1. Type the first sentence to match the length of the composer.
2. Press the Carriage Return button.
3. Start the next sentence on a new line.

**What actually happens:**
1. Type the first sentence to match the length of the composer.
2. Press the Carriage Return button.
3. New lines are removed.
4. The expanded box contracts.

It happens both on reply and non-reply msgs. 

### software info 

* Element X 0.4.0 
* Android 14

**Comment by jmartinesp** [comment]
I believe this should be fixed in https://github.com/matrix-org/matrix-rich-text-editor/pull/916. Once we release a nightly with these changes I'll let you know so you can test it, if you want to.

**Comment by spongythecake** [comment]
Great. I'd be willing to use nightly.

**Comment by manuroe** [comment]
Tested on 0.4.8-nightly. It is fixed. Thanks @jmartinesp

**Comment by spongythecake** [comment]
Still experiencing this issue on 0.4.9.
