### ISSUE TITLE
Read receipt avatars & names sometimes fail to show until the room is reopened

### ISSUE THREAD

**Issue by surakin** [element-hq/element-x-android#2176]
### Steps to reproduce

1. Start Element X, open any room
2. Notice how some read receipt avatars are missing and you just see the initial
3. Go back and open the same room again
4. Avatars show up.

(It doesn't happen 100% of the times)

#### What did you expect?
Avatars should always show up (eventually)
#### What happened instead?
They don't show up until the room is reopened

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by jmartinesp** [comment]
Note: this seems to affect iOS too, so it's either a coincidence or it's related to how we get this info from Rust.

**Comment by jmartinesp** [comment]
Apparently, it's a coincidence. It was our caching working against us. As the saying goes:

> There's only 2 hard things on computer science: cache invalidation, naming things, and off-by-one errors
