### ISSUE TITLE
Biometric Unlocking

### ISSUE THREAD

**Issue by K4LCIFER** [element-hq/element-x-android#2180]
#### What would you like to do?

I would like to have the ability to unlock Element X using the biometric features of the device that Element X is installed on.

#### Why would you like to do it?

Enhanced security, and ease of use.

#### How would you like to achieve it?

Prompt for biometrics before loading the app at startup.

### Have you considered any alternatives?

No.

### Additional context

This would fall under the "Screen lock" setting.

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
Biometric unlock is already supported:

<img width="346" alt="image" src="https://github.com/element-hq/element-x-android/assets/480955/692898bf-4fd0-46ce-a015-92a461e6f5e2">

Are you maybe using an old version of the app?

**Comment by K4LCIFER** [comment]
Ah, I see now -- I didn't realize that I had to first make a pin before the biometric unlocking option was showed. It makes sense, though. Perhaps it would be better to show the option, but greyed out, so that the user, at least initially knows that it exists.

**Comment by bmarty** [comment]
I agree with the idea @K4LCIFER , but this is not really possible without fully changing the flow. Currently when there is not PIN set up and the user clicks on `Screen lock` from the main setting screen, the user is prompted to choose a PIN code.

This could be revisited but I do not think this is a priority at the moment.
