### ISSUE TITLE
Some rooms/chats are missing in the list

### ISSUE THREAD

**Issue by life00** [element-hq/element-x-android#2203]
### Steps to reproduce

1. previously join many rooms/chats from other client (I have 20+)
2. install Element X and login
3. look at the list of rooms

#### What did you expect?

App displaying all rooms .

#### What happened instead?

App displaying *some* rooms.

### Your phone model

pixel 6a

### Operating system version

Android 14 (latest release)

### Application version and app store

Element X v0.4.0 from GitHub releases

### Homeserver

tchncs.de Synapse 1.98.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by life00** [comment]
Sorry I can't send the logs cuz I already deleted everything. If its difficult to reproduce then I'll send the logs.

**Comment by bmarty** [comment]
Hello @life00 and thanks for reporting. Do you see any common state for the missing room? i.e. all your favorite rooms are missing, or all the room for a specific space, or whatever.
Asking because this issue has not been reported before, and is quite annoying.

You also have the option to clear cache, from the settings, to see if it fixes the issue. Let me know if it is the case.

**Comment by life00** [comment]
It is indeed a very annoying bug. I would say it makes the client mostly unusable.

Your suggestion about clearing cache doesn't help. It seems that the bug occurs and persists from initial startup, or it is something to do with room properties.

I honestly have no idea which characteristics cause it because some DMs with a user from matrix.org disappear, but it worked when DMing you. Also some matrix.org rooms are missing, but some are there. I only noticed that GrapheneOS rooms and tchncs.de discussion are always there.

**Comment by life00** [comment]
It also seems like all matrix bridge rooms are missing?

**Comment by life00** [comment]
I think it would be helpful if you'll be able to reproduce this on your debug setup. I can tell you which rooms are not displayed and if its reproducible then its caused by some room properties, otherwise it would be something else. For example I done see #keepassxc:mozilla.org , #asahi:fedoraproject.org , #bash:matrix.org .

**Comment by jmartinesp** [comment]
FWIW I can see all those rooms:

<details>
<summary>Screenshot</summary>

<img width="412" alt="image" src="https://github.com/element-hq/element-x-android/assets/480955/c373923f-d8a3-43cf-9dd9-46f84d81c162">

</details>

So it's probably not the rooms themselves that are problematic, but maybe some weird corner case we haven't identified yet.

**Comment by jmartinesp** [comment]
Oh, in the logs I see:

```
2024-01-11T16:39:39.766031Z ERROR elementx: Failed updating visible range
org.matrix.rustcomponents.sdk.RoomListException$InputCannotBeApplied: 
	at org.matrix.rustcomponents.sdk.FfiConverterTypeRoomListError.read(SourceFile:74)
	at org.matrix.rustcomponents.sdk.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(SourceFile:13)
	at org.matrix.rustcomponents.sdk.FfiConverterTypeRoomListError.liftFromRustBuffer(SourceFile:1)
	at org.matrix.rustcomponents.sdk.FfiConverterRustBuffer$DefaultImpls.lift(SourceFile:6)
	at org.matrix.rustcomponents.sdk.RoomListException$ErrorHandler.lift(SourceFile:8)
	at org.matrix.rustcomponents.sdk.Matrix_sdk_ffiKt.access$checkCallStatus(SourceFile:114)
	at org.matrix.rustcomponents.sdk.Matrix_sdk_ffiKt.uniffiRustCallAsync(SourceFile:184)
	at org.matrix.rustcomponents.sdk.RoomListService.applyInput(SourceFile:79)
	at io.element.android.libraries.matrix.impl.roomlist.RustRoomListService$updateAllRoomsVisibleRange$1.invokeSuspend(SourceFile:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```
	
Now this is interesting. I don't think I've seen it before, but it gives us something to work with.

**Comment by life00** [comment]
ok, uhm... I am not sure what happened, but now I see those rooms that I've mentioned. This happened after some time of inactivity and a resync. But there are still rooms and DM's that I do not see.

**Comment by jmartinesp** [comment]
This seems more like a sliding sync problem then. Can you share some of the rooms you're missing? FWIW, I tried creating an account in your server and adding your missing rooms as well as some others and DMs but I couldn't reproduce your issue. Some rooms took a few seconds to appear after being joined, but that was all.

Also, about the stacktrace above, I'm sorry to say it's not something that could cause the issue you're seeing.

**Comment by jmartinesp** [comment]
Now that I think about it, having the sliding sync logs for your user in that server would be super valuable here, but I guess it's not something you can just ask the admins. It would be a lot easier to debug if this had happened on one of our servers 😞 .

**Comment by life00** [comment]
> This seems more like a sliding sync problem then. Can you share some of the other rooms you're missing? FWIW, I tried creating an account in your server and adding your missing rooms as well as some others and DMs but I couldn't reproduce your issue. Some rooms took a few seconds to appear after being joined, but that was all.
> 
> Also, about the stacktrace above, I'm sorry to say it's not something that could cause the issue you're seeing.

It seems that it is not room related. If you want to try reproducing it then you'll have to add a lot of rooms. As I said 20+

Also I recommend first joining rooms you want to test and only then logging into Element X. The rooms that are currently missing for example are: #lazyvim:matrix.org , #syncthing-support:matrix.org , DM's and a bunch of other not so popular rooms. Interestingly mostly unpopular rooms are missing.

**Comment by jmartinesp** [comment]
FWIW I tried using the same account as before on your server, added a few 10+ rooms (including the ones you mentioned above), large and small ones, and a couple of DMs until I had ~35 rooms in total and I still couldn't reproduce the issue, all of the rooms and the DMs were present. Maybe the SlidingSync proxy at your server is having some issues with your account? I think it'll be very difficult to know what's actually happening without logs from this proxy, and those aren't public...

**Comment by life00** [comment]
I will later try experimenting with a matrix.org home server.

**Comment by spaetz** [comment]
One idea if mistly unpopular rooms are.missing: could it be that the direct connectiin to matrix.org is blicked/blacklisted by the users homeserver or by matrix.irg? In this case only events with common 3rd party homeservers would be relaying events, which could explain why more popular rooms always appear.

But all that is just speculation

**Comment by manuroe** [comment]
@life00 do you still see this issue on your homeserver?

**Comment by life00** [comment]
> @life00 do you still see this issue on your homeserver?

@manuroe no, I am no longer able to reproduce it on tchncs.de with ~10 rooms and few DMs. All are displayed.
