### ISSUE TITLE
Notifications are quite delayed

### ISSUE THREAD

**Issue by bkchr** [element-hq/element-x-android#2209]
### Steps to reproduce

I'm trying out the new Element X on my Android mobile phone. My problem is that notifications take quite long to appear on my device (at least 30min). If I open the app, I can directly see all the messages. If I read the messages, I still get some of the notifications after the delay. When I then click on the notification, it doesn't disappear. 

#### What did you expect?

Notifications are almost instant.

#### What happened instead?

Notifications are taking at least 30 minutes, most of the time even longer.

### Your phone model

S23 Ultra

### Operating system version

Android 14

### Application version and app store

0.4.2-nightly (40004020)

### Homeserver

matrix.parity-stg.parity.io

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by bkchr** [comment]
If any kind of logs from the device can help, please tell me what you need. I can connect adb to fetch logs.

**Comment by T-bond** [comment]
I also experiencing this. Also, if I read the message on Element Web, the notification still arives later on phone for EAX.

**Comment by spongythecake** [comment]
Did you give Element X unrestricted battery ? Some Android flavours use tricks to save power and notifications can be a target when set to optimised.

**Comment by bkchr** [comment]
Embarrassing, yeah Samsung has by default "optimized power settings" which apparently interferes with the app... I deactivated it for the app and getting notifications. While I see the messages in the notification, they don't appear in the chat, even my own messages in the chat disappear 😅

**Comment by bkchr** [comment]
Maybe the messages not showing is related to me not having the backup setup?

**Comment by spongythecake** [comment]
> Embarrassing, yeah Samsung has by default "optimized power settings" which apparently interferes with the app... I deactivated it for the app and getting notifications. While I see the messages in the notification, they don't appear in the chat, even my own messages in the chat disappear 😅

Never be embarrassed. It's not your fault. Samsung gives priority to some popular apps like WhatsApp for notifications, meaning favouritism can cause confusion.

**Comment by T-bond** [comment]
I also just changed from optimised. The app is pinned to the recents, I thought it was enough. I will see if the problem persists.

**Comment by manuroe** [comment]
Closing it as it was due to an OS preference setting.
The notification troubleshoot screen like on the legacy Element Android app could have helped to show the problem earlier. We discussed about it in #185 but we have not implemented it yet.

**Comment by bkchr** [comment]
Hmm, it stopped working again for me 👀 Battery settings are still set to unoptimized.

**Comment by claell** [comment]
I have heard this for Instagram, too. Basically, users set the app to unoptimized, but notifications still don't arrive on time. (This is just hearsay, though).
My speculation is that the app uses a background service for notifications, which is unrelated to the normal app. So the phone kills/"optimizes" the notification service (that gets "optimized"), not the app (that is allowed to consume battery). This speculation of separation between app and notification service can be observed, when notifications don't appear, even after actively opening the app.
