### ISSUE TITLE
Add Possibility to connect with Google Account

### ISSUE THREAD

**Issue by Pegasus4903** [element-hq/element-x-android#2227]
#### What would you like to do?

I would love to be able to connect to the new Element X app with my Google account, knowing that it is possible on the classic element app.

#### Why would you like to do it?

Because my account was created with my google account and I can't connect to it.

#### How would you like to achieve it?

Whether by adding a button option on the connecting screen or by adding a new provider in the choices availables.

### Have you considered any alternatives?

Yes, I use the classic app to chat. But I really want to try the new one and add feedback.

### Are you willing to provide a PR?

No

**Comment by Pegasus4903** [comment]
Regarding the PR, if it means that i'm doing my own pull request, i'm afraid I can't provide my touch to the project for personal reasons.

**Comment by bmarty** [comment]
This will be covered by OIDC

**Comment by Pegasus4903** [comment]
> This will be covered by OIDC

OIDC ?
