### ISSUE TITLE
[Task] Show that a users role has changed in the room timeline

### ISSUE THREAD

**Issue by pixlwave** [element-hq/element-x-android#2260]
Please see and discuss the details in the meta issue.

**Comment by bmarty** [comment]
Need some change SDK side to provide more information. Then the code will not compile and will have to be updated [here](https://github.com/element-hq/element-x-android/blob/develop/libraries/eventformatter/impl/src/main/kotlin/io/element/android/libraries/eventformatter/impl/StateContentFormatter.kt#L173).
