### ISSUE TITLE
cannot log in

### ISSUE THREAD

**Issue by TeFiLeDo** [element-hq/element-x-android#2305]
### Steps to reproduce

1. Start on the login screen
2. Change account provider to `tfld.dev`
3. Click continue

#### What did you expect?
Some kind of dialog for loggin in.

#### What happened instead?
An error message opens:

```txt
We couldn't reach the homeserver. Please check that you have entered the homeserver URL correctly. If the URL is correct, contact your homeserver administrator for further help.
```

### Your phone model

Google Pixel 6

### Operating system version

Android 14

### Application version and app store

Element X Version 0.4.1 - Google Play Store

### Homeserver

Synapse 1.99.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

### Notes

1. The exact same server setup worked in the past. It stopped working when I logged out. There was no change on the server side.
2. I also tried setting the account provider to `sliding.matrix.tfld.dev` (which is also the proxy set in the `.well-known/matrix/client`). When entering it into the search field, no result pops up.
3. I my server access log, I only see the request to the `.well-known/matrix/client` file. There is no subsequent request to the proxy.

**Comment by bmarty** [comment]
The error is quite generic and does not help a lot.
The underlying Exception is `java.lang.IllegalStateException: Unsupported login flow`.

**Comment by TeFiLeDo** [comment]
Ah, I think I understand now. When reading the OIDC requirement I thought I satisfied it, as I had configured OIDC in synapse a long time ago. I didn't realize it meant the new auth system.

That means that I broke it a while ago and just didn't notice, and that I have an access log to fix.

Thanks for your help
