### ISSUE TITLE
Show device ID in settings

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-android#2316]
### Steps to reproduce

1. try to find your device ID
2. on EXI, it's listed next to the version string on the Settings page
3. on EXA, it isn't, and i can't find it.

#### What did you expect?

A way to find out my device ID

#### What happened instead?

Lost, lost without hope

### Application version and app store

0.4.2 trinity

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
(in the meantime the `deviceId` is printed out in the rageshake description if it helps)
