### ISSUE TITLE
Device verification: Emoji names are not translated

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-android#2321]
From element-x-ios created by [manuroe](https://github.com/manuroe): element-hq/element-x-ios#2402  

### Steps to reproduce

1. Configure the app to use another language than English
2. Log in the app
3. Start verification with another matrix client
4. The emoji names in the verification screen is in English instead of using the app language you selected

#### What did you expect?
Emoji names should be translated

#### What happened instead?
Emoji are in English

![IMG_9648](https://github.com/element-hq/element-x-ios/assets/8418515/8a82b5cb-51d3-444b-a09f-0e87f74798ea)

### Will you send logs?

No

**Comment by bmarty** [comment]
Emoji are translated on EXA, since https://github.com/element-hq/element-x-android/pull/1965
