### ISSUE TITLE
Failing OIDC setup probably related to the Rust SDK (cannot create OIDC registration store)

### ISSUE THREAD

**Issue by lennart-k** [element-hq/element-x-android#2352]
### Steps to reproduce

- Setup Matrix server with matrix-authentication-server OICD, etc.
- (Verify it works on Element Desktop, it does :))
- (Verify all the requests from Element X yield a reasonable response :))
- Select matrix server in Element X android app
- "You're about to sign in", continue
- **Error**: We couldn't reach this homeserver.

After looking through the logs I believe this is actually a bug in the Rust SDK since it fails creating the OIDC registration store, see https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk/src/oidc/registrations.rs#L167.
![image](https://github.com/element-hq/element-x-android/assets/18233294/ac9882b8-083d-4c25-aeb4-2cb77c082cde)

By the way it also fails in the same way on iPadOS. However, there I cannot debug anything.

#### What did you expect?

After clicking "Continue" I would've expected a redirection to the SSO provider (MSA) :)

#### What happened instead?

Error: "We couldn't reach this homeserver"
`matrix_sdk::oidc::registrations: Failed to load registrations file: No such file or directory (os error 2) | crates/matrix-sdk/src/oidc/registrations.rs:167`

### Your phone model

Google Pixel 5

### Operating system version

Android 14

### Application version and app store

Element X 0.4.2

### Homeserver

diewolke.dev with Synapse, MAS, sliding sync

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
I was able to debug the issue a bit and I saw this was the underlying error (we should probably have better error messages here, sorry):

```
OidcError(type=OidcException, message=An error occurred with OIDC: issuer URLs don't match)
```

It seems like an issue with the OIDC configuration.

**Comment by lennart-k** [comment]
Thank you so much for debugging. Your error message quickly helped me find out I had a trailing slash missing in the well-known configuration.

**Comment by kosmos** [comment]
@lennart-k Exactly what config parameter did you not have a slash in?

**Comment by kosmos** [comment]
@jmartinesp Could you please tell me if you have changed the error message yet, or if it looks the same now? Since I am facing the same error and trying to find the cause of it.
