### ISSUE TITLE
Encrypted history stopped loading

### ISSUE THREAD

**Issue by surakin** [element-hq/element-x-android#2393]
### Steps to reproduce

1. Where are you starting? What can you see?

Since commit https://github.com/element-hq/element-x-android/commit/6dc0d8706c80d67a3188f4d9c8f761d6feaa3d71 encrypted history won't load.

![image](https://github.com/element-hq/element-x-android/assets/683652/08479d53-444f-4a47-b98b-d5e9a9871a70)

A build from the previous commit works just fine 

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
This should be fixed after https://github.com/matrix-org/matrix-rust-sdk/pull/3131 is merged and a new Rust SDK version is integrated.
