### ISSUE TITLE
RecoveryKey | App still not happy after asking me to confirm my recovery key

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-x-android#2398]
## Step to reproduce (?):

- Using a web session, reset your backup.
- EAX should then ask you to confirm your recovery key

## Actual
Recovery key is successfully entered, but EAX is still asking to confirm.

![screen](https://github.com/element-hq/element-x-android/assets/9841565/e5b3671a-fa1d-4494-8138-677a8951e382)

A kill/restart fixes it

## Expected

Should be fine after I entered the confirm key

https://github.com/element-hq/element-x-android-rageshakes/issues/1489

**Comment by spaetz** [comment]
https://github.com/element-hq/element-x-android/issues/2098

**Comment by bmarty** [comment]
This has been fixed in https://github.com/element-hq/element-x-android/pull/2421, there was an issue on the state observer.

Can you confirm it's fixed on the latest nightly and/or on EXA 0.4.5?

If not, feel free to re-opne the issue.

**Comment by Axolord** [comment]
Issue still persists for me, on EXA 0.4.5
