### ISSUE TITLE
Empty chat screen looks unfinished

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#2461]
### Steps to reproduce

1. Open EAX without any chats

#### What did you expect?
Some nice screen onboarding me into the first chat

#### What happened instead?
Screen with unformatted and redundant text

![Screenshot_20240228-210318](https://github.com/element-hq/element-x-android/assets/640121/1ac098fc-74cd-455c-b923-397a7d13e267)

- _Noch keine Chats_ is redundant as obviously there are no chats, so why write this?
- _Beginne ..._ is redundant as obviously to start a chat you need to start a chat. It's also not well formatted

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks for creating the issue. I have seen the alignment problem today while working on screenshot test for other languages than English, and I will fix it.

For the wording content, itself, I believe there is some work on empty state relating to the new filters. Here is the current English version:

<img width="300" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/c14b74f7-9cd3-418e-9628-1592f8f1f90d">

This is maybe a translation issue? To change the English version, I suggest talking with @amshakal and @VolkerJunginger first.

**Comment by kongo09** [comment]
Great.

Text is essentially the same text in English. Mid-term I would expect some illustration or so, but for now that's surely not urgent.

**Comment by bmarty** [comment]
OK.

Additionally we may want to hide the filters if the account has no rooms CC @ganfra .
