### ISSUE TITLE
Filter bubble is half hidden when floating to front after selection

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#2462]
### Steps to reproduce

1. Open EAX in room list
2. Scroll to the end of the list of filter bubbles
3. Select the last one

#### What did you expect?

- Filter is selected
- As it floats to the front, I would expect it to be fully visible

#### What happened instead?

- Filter bubble is half hidden behind a new X that appears (which is redundant anyhow if only one filter bubble is selected)
- This doesn't happen when any filter bubble is selected (including the last one) without first scrolling the list of bubbles

![image](https://github.com/element-hq/element-x-android/assets/640121/382bafec-6891-4e0e-8cda-f06830ed5b11)

### Your phone model

Pixel 5

### Operating system version

Android 14

### Application version and app store

0.4.6-nightly

### Homeserver

element.io

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Assigning to @ganfra who worked on this.
Filtering rooms is at early stage of development, and we are currently iterating on it.
CC @amshakal
