### ISSUE TITLE
Filter bubbles seem part of the header but don't show the blur in the background

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#2463]
### Steps to reproduce

1. Open EAX
2. Scroll down the room list a bit

#### What did you expect?

- filter bubbles stay at the top as part of the header
- the blur from the avatar goes into the background

#### What happened instead?

- filter bubbles seem to be a line of their own, which gives them a disconnected feeling

![image](https://github.com/element-hq/element-x-android/assets/640121/84ab9d01-c616-4033-a49d-948a015a0a69)

Extending the blurring could be a solution. However, what I truly would expect is for the rest of the header to get out of the way once you scroll down the room list, like WhatsApp or Telegram.

https://github.com/element-hq/element-x-android/assets/640121/f7cfcbf2-4c1f-4ad9-b9f0-d8ac9b5b69fb

### Your phone model

Pixel 5

### Operating system version

Android 14

### Application version and app store

0.4.6-nightly

### Homeserver

element.io

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Assigning to @jmartinesp as I think he started working on this.

**Comment by jmartinesp** [comment]
I actually gave @ganfra a patch that should have solved this, so I don't know if it wasn't implemented following some designs  or he just meant to iterate on it later.
