### ISSUE TITLE
Hide "Blocked users" menue item if the user has no blocked user

### ISSUE THREAD

**Issue by VolkerJunginger** [element-hq/element-x-android#2469]
### Your use case

Hide "Blocked users" menue item if the user has no blocked users.

### Are you willing to provide a PR?

Yes

**Comment by davidegirardi** [comment]
I personally like to have a "blocked users" menu always visible so I know where to find it if I'll ever need it.

**Comment by jmartinesp** [comment]
> I personally like to have a "blocked users" menu always visible so I know where to find it if I'll ever need it.

That's the same reasoning we initially had when we implemented it. I'm not sure what changed in the meantime.

**Comment by bmarty** [comment]
Maybe another solution is to add some screen hierarchy in the settings, because the setting root screen is becoming a long list of unrelated topics.

**Comment by VolkerJunginger** [comment]
We have a clean up epic https://github.com/element-hq/element-internal/issues/561 to target that!
