### ISSUE TITLE
New messages sometimes appear on top of visible timeline for a few seconds

### ISSUE THREAD

**Issue by rom4nik** [element-hq/element-x-android#2491]
### Steps to reproduce

1. Have app closed (iirc happened a few times when it was just backgrounded, and when had it in foreground but my phone was sleeping for 15-30 mins?)
2. Receive a notification about new message in room
3. Tap the notification

#### What did you expect?
When timeline becomes visible (ideally without waiting 5s...), it's complete and the new messages are immediately visible at the bottom.

#### What happened instead?

https://github.com/element-hq/element-x-android/assets/46846000/62b512c8-7d73-4d15-87fe-eedbfee1ea3c

The most recent part of timeline appears instantly, then after 3-4s the upper part of timeline appears with the new message now put in between old messages, then a second later entire timeline reloads and the new message is at the bottom.

### Your phone model

Google Pixel 7 Pro

### Operating system version

Android 14

### Application version and app store

0.4.5 release build

### Homeserver

Synapse v101.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
It definitely looks like an issue with the timeline pagination, probably on the app side.
