### ISSUE TITLE
`Session key` unexpectedly gets copied to clipboard when tapped (`Access Token` too) - it's a feature though

### ISSUE THREAD

**Issue by correabuscar** [element-hq/element-x-android#2492]
### Steps to reproduce

1. Where are you starting? What can you see?
in `Settings` -> `Security & Privacy`, you see `Session key` and the actual session key text below it there,

2. What do you click?
if you tap Session key or the key text itself, you get a toast notification that it was "Copied to clipboard"

#### What did you expect?
to not copy it to clipboard - it's an obvious security issue

#### What happened instead?
got copied to clipboard, so any potential apps monitoring the clipboard(pre android 10, right?) likely snatched a copy too, maybe even sent it back home via the internet already.

When I tap it, I don't know it will get copied to clipboard, if I knew, I would NOT have tapped it. So, maybe a confirmation dialog if u really want it copied to clipboard would be a solution, or just don't copy it at all. Why is it even needed? Can it be used for something? (this Session key I mean)

Same thing applies to something else which I understand it can be used for something, but it's still unexpected that tapping it would copy it to clipboard thus giving it away to any clipboard monitoring apps running in the background:
`Settings` -> `Advanced settings` then at the very bottom is `Access Token` with its description `Your access token gives full access to your account. Do not share it with anyone.`
But what happens if you tap it? `Copied to clipboard` !!! I was fuming, at this point I can consider myself compromised. It's just unbelievable that this is a thing. Now granted that `Developer mode` setting has to be enabled for this `Access Token` to be ungreyed and only then is thus copiable, but still: I didn't expect it to be copied to clipboard without permission first.

on android 6.0 I've Element version 1.6.12 [4010612**1**] (G-effdca18)
but on android 13 it's Element version 1.6.12 [4010612**2**] (G-effdca18)
which is kind of odd.

<details>

> Whether other apps can be notified and access the clipboard contents depends on the operating system and specific app behavior:

>Android:

>    Prior to Android 10: Apps could freely access the clipboard content, even in the background. This raised privacy concerns.
>    Android 10 and above: Only the following apps can access the clipboard:
>        The app currently in focus: This is the app you're actively using when copying something.
>        The input method editor (IME): This is the keyboard app you use for typing.
>    Android 12 and above (optional): Users can enable a feature that notifies them whenever an app accesses the clipboard.

( I can't find it on my xiaomi android 13 - and 
> "The feature to enable clipboard access notification is not currently available on Xiaomi devices running Android 13.0.4."

)

>iOS:

>    Before iOS 14: Apps could access the clipboard content while they were in the foreground.
>    iOS 14 and above: Apps can still access the clipboard content, but:
>        They can only do so while they are in the foreground.
>        New in iOS 15: Users can enable a feature that shows a notification whenever an app accesses the clipboard.

from Gemini.

</details>

### Your phone model

ALLVIEW

### Operating system version

6.0

### Application version and app store

1.6.12 [40106121] (G-effdca18)

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by jmartinesp** [comment]
I see how this behaviour can be unexpected. If I'm not mistaken, what was copied was the device id, which I believe isn't useful by itself. I think logging out and in again would generate a new one.

However, this is the repo for the Element X app, not [Element](https://github.com/element-hq/element-android). You can open an issue there, but please not that development of the Element app has been mostly paused so we can focus in this client instead.

**Comment by correabuscar** [comment]
My bad, apologies! Also apologies for the tone (I shouldn't make bug reports when angry/etc.)

To clarify, it is not the `Session ID`(which is above), it is the session key that is copied, the one that's shown beneath the `Session key`(but only shown when online/connected like when wifi is on, and persists until logout(it changes on login but how often does that happen - could be years) but this can remain unchanged for years without a logout, if you don't log out manually or reinstall the app) as a group of 10x4 chars and another 3 chars after, but is copied into clipboard without any spaces. Same for `Access Token`, it's the access token, no spaces, except that this isn't shown on the screen at all, unlike `Session key` which is visible on screen(but only when app is online).
