### ISSUE TITLE
Device not receiving to-device messages

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-x-android#2520]
### Steps to reproduce

Filing this here for want of a better place; it's as likely to be a bug in Synapse, the sliding sync proxy, or the rust SDK as in EXA itself.

We have a rageshake from an EXA user who reports a decryption failure. The UTD appears to be due to the to-device message carrying the room key not arriving (we have logs which show it being sent by the sending client).

What is *particularly* odd is that, in the lifetime of the logs we have from this device (spanning over 24 hours), I don't see a *single* to-device message being received by the crypto stack. 

I'm not really sure how to go about debugging this, particularly since we don't have logs from either homeserver, nor the sliding-sync proxy, but I wanted to record the issue in case it rings any bells for anyone.

CC @frebib, who sent the rageshake (thank you!)

#### What did you expect?

To-device messages received and logged

#### What happened instead?

No to-device messages

### Operating system version

Android 14

### Application version and app store

0.4.3, GooglePlay

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
@poljar may have some inputs to give here. I am not sure how to device Event management is printed out by the SDK and so if they appear in the rageshake logs.

**Comment by poljar** [comment]
> @poljar may have some inputs to give here. I am not sure how to device Event management is printed out by the SDK and so if they appear in the rageshake logs.

We print the count of received to-device events here: https://github.com/matrix-org/matrix-rust-sdk/blob/a204b2994d4c5d58c4769e767f61fc7db7546e38/crates/matrix-sdk-base/src/sliding_sync.rs#L66-L72

**Comment by kegsay** [comment]
This sounds exactly like https://github.com/matrix-org/sliding-sync/issues/448

**Comment by kegsay** [comment]
Confirmed that frebib may have been hit by that. The latest version (unreleased but on main) of the proxy guards against dropping to device messages after a dropped db.

I suspect we can close this issue once the corresponding sliding sync issue is closed.

**Comment by kegsay** [comment]
Closing this on the assumption this was https://github.com/matrix-org/sliding-sync/issues/448
