### ISSUE TITLE
MatrixRTC duplicate rooms

### ISSUE THREAD

**Issue by YourSandwich** [element-hq/element-x-android#2528]
### Steps to reproduce

1. Join Voice Call on Element Desktop
2. At the same time or before Element X syncs the room, join the Conversation

#### What did you expect?
The Room should have one Voice chat

#### What happened instead?
Element X created a new Call session instead of joining the originally created one by Element Desktop

### Application version and app store

0.4.5

### Homeserver

1.101

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by manuroe** [comment]
We need to spend time to investigate this.

**Comment by YourSandwich** [comment]
Didn't experience this bug for a while. It may be gone by now.

**Comment by manuroe** [comment]
thanks @YourSandwich for the feedback. I am closing this issue.
