### ISSUE TITLE
Profile pics lost in timeline

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#2530]
### Steps to reproduce

1. Enter room (in that case with 4 participants)
2. Observe timeline

#### What did you expect?
See profile pics for the conversation

#### What happened instead?
No profile pics, so it's unclear who said what

![Screenshot_20240311-224336](https://github.com/element-hq/element-x-android/assets/640121/2ce83f7b-1f52-4b07-be92-8e66d285d48b)

### Your phone model

Pixel 5

### Operating system version

Android 14

### Application version and app store

0.4.6-nightly

### Homeserver

element.io

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by frebib** [comment]
This at least happens if a chat starts as a DM then another participant is added
![Screenshot_20240312-123311.png](https://github.com/element-hq/element-x-android/assets/775104/81449298-216d-41b6-aa0e-8f89694d2cd3)

**Comment by bmarty** [comment]
There is an issue, we are using `isDirect` instead of `isDm`. @ganfra will fix.
