### ISSUE TITLE
[Element Call] Remove blue click indicator in WebView

### ISSUE THREAD

**Issue by TheDidek** [element-hq/element-x-android#2555]
#### What would you like to do?
Remove the blue rectangle being shown when pressing clickable elements in WebView that Element Call uses.

Example:
![Screenshot_20240315-033413_Element X_1](https://github.com/element-hq/element-x-android/assets/145149410/8447a864-0a5c-4f13-bb97-4c040a499282)

#### Why would you like to do it?
Such indication does not fit Element X design and makes it obvious that the calling interface is a rendered web app, breaking visual consistency. It would look better to have custom effect like darkening the color of pressed button.

#### How would you like to achieve it?
One of the ways is to add ```-webkit-tap-highlight-color:``` CSS declaration.

### Are you willing to provide a PR?

No

**Comment by toger5** [comment]
Thank you so much for the details!
I waas really annoyed by this as well but never had an insentive to give that priority. You provided the needed momentum.
