### ISSUE TITLE
Update room member list contents after changing member roles

### ISSUE THREAD

**Issue by VolkerJunginger** [element-hq/element-x-android#2590]
### Steps to reproduce

Userflow:
- Invite a new user to a room
- The user does not accept the invite
- Go to moderation make that pending user an admin
- Go to the member list

Android does not show that the pending member is an admin - iOS does.

To Do

Show user-role for pending members.

Side-note
Yes, it makes sense to be able to change the role of a future member. This way I can invite someone and then already give them the right role and don't have to come back later.

![Screenshot](https://github.com/element-hq/element-x-android/assets/118339066/f0186dd7-bf7b-464d-8328-3882ff6bdc7e)

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by ganfra** [comment]
@jmartinesp do u take the point ?

**Comment by jmartinesp** [comment]
Yup, already checking it. If I'm not mistaken the problem isn't that we don't display roles for pending users, it's that the list isn't updated: if I get out of the room screen and enter it again the members are reloaded and they display the right roles.

It's a side effect of https://github.com/element-hq/element-x-android/pull/2564 being too restrictive.
