### ISSUE TITLE
Crash on RustMatrixRoom.activeMemberCount

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#2619]
**IllegalStateException**
Room object has already been destroyed

<img width="1138" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/cbbbde58-9c18-42fe-afbf-f845ad9d9ef8">

Seems that the room is release and the timeline is still active.

Crash occurrence is low but would be nice to investigate and fix. Investigating it.

**Comment by ganfra** [comment]
We should probably try catch all those `val`, because this could happen in several places :/ 
We could also try to rely on autocleaner instead of destoying manually the inner room.
