### ISSUE TITLE
[Task] Sign in with QR code

### ISSUE THREAD

**Issue by stefanceriu** [element-hq/element-x-android#2632]
From element-x-ios created by [stefanceriu](https://github.com/stefanceriu): element-hq/element-x-ios#2622  

Please see and discuss the details in the meta issue.

**Comment by hughns** [comment]
Code is in https://github.com/element-hq/element-x-android/compare/develop...feature/bma/signInWithQrCode

**Comment by LecrisUT** [comment]
Is this not available on matrix.org server? I don't see any sign-in with qr code button in the initial onboarding screen

**Comment by hughns** [comment]
You are correct. Currently the matrix.org homeserver does not have the necessary features enabled to support the Sign in with QR feature.

**Comment by LecrisUT** [comment]
Could someone update https://github.com/element-hq/element-meta/issues/1915?

Something similar to

> - No OIDC support yet on the matrix.org homeserver

The situation is not great because matrix.org users who created their accounts with OAuth login cannot login. Unless they create a password for which I don't remember if it had some gotchas as well.
