### ISSUE TITLE
Show name of day on day markers

### ISSUE THREAD

**Issue by azizLIGHT** [element-hq/element-x-android#2637]
#### What would you like to do?
When the day changes over at 12 am, a day marker notes the change in date. This day marker does not indicate the name of the day
#### Why would you like to do it?
To know what day it has become, or what day a particular date was as I scroll back through chat logs
#### How would you like to achieve it?
Instead of it saying "April 1, 2024" it can say "Monday, April 1, 2024". The usefulness matters more for dates further in the past

### Have you considered any alternatives?

- Opening a calendar app
- Relying on memory 

### Are you willing to provide a PR?

No

**Comment by spaetz** [comment]
I think https://github.com/element-hq/element-x-android/pull/3057 could resolve this issue? If yes, this one can be closed.

**Comment by jmartinesp** [comment]
> I think #3057 could resolve this issue? If yes, this one can be closed.

Yes, it should. Thanks for the reminder!
