### ISSUE TITLE
cannot click on room links in messages

### ISSUE THREAD

**Issue by jclulow** [element-hq/element-x-android#2641]
### Steps to reproduce

If you receive a message with a link to a room in it; e.g., as HTML:

```
<a href="https://matrix.to/#/!DBwVoaYOBwhtXPRTHb:oxide.computer">#oxide-test-chamber</a>
```

My client is joined to the room.  I can select it from the room list and participate in the room.

The link is correctly turned into a bubble that just has the name of the room, a bit like in the Element desktop/web client.

When pressing the link with my finger, nothing happens.  I have pressed many times, but I never end up in the room in question.

#### What did you expect?

To go with the client to a second location.

#### What happened instead?

I remained in the original room, where the link was rendered.

### Your phone model

Google Pixel 8

### Operating system version

Android 14

### Application version and app store

v0.4.7 from Play Store

### Homeserver

Synapse 1.102.0 with Sliding Sync Proxy 0.99.15

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Yes, this will be handled by #2642.
