### ISSUE TITLE
Odd typing behavior after non-alphanumeric characters (OpenBoard Keyboard)

### ISSUE THREAD

**Issue by 0x1a8510f2** [element-hq/element-x-android#2682]
### Steps to reproduce

1. Be on GrapheneOS with OpenBoard keyboard.
2. Open any room on ElementX Android and type any text.
3. Enter non-alphanumeric character such as `.` or even ` ` (space).
4. Note weird duplicated characters when typing or deleting text.

https://github.com/element-hq/element-x-android/assets/83190128/35a5a984-bda4-4a1f-bd0d-d8e8f49c1a16

### Outcome

N/A

### Your phone model

Google Pixel 8 Pro

### Operating system version

Graphene OS (2024040300)

### Application version and app store

Version 0.4.7 io.element.android.x versionCode 40004070 (play store)
OpenBoard 1.4.5 (fdroid)

### Homeserver

Dendrite 0.13.7

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by mrclauss** [comment]
https://github.com/element-hq/element-x-android/assets/70584097/479258c6-4749-4328-b34a-599a19bf2006

Same here on Redmi Note. Worst thing is that you cannot delete the first letter of any word...

**Comment by mrclauss** [comment]
To me this looks like if the keyboard is reconfigured after every character...

**Comment by mobergmann** [comment]
Same problem for me. I am using a Fairphone 4 with the default Android and  the HeliBoard keyboard.

**Comment by mobergmann** [comment]
PS: the problem does not appear when using the Google Keyboard or when using Schildi Next

**Comment by mobergmann** [comment]
> Fascinating. For me the error disappeared after updating gboard! Thanks @mobergmann for your comment

So you suggest its rather an issue with the keyboard and not the app?

**Comment by mrclauss** [comment]
I would rather say that it's an issue in the interaction between app and keyboard that might be tolerated by some keyboard versions...


Am 12. April 2024 11:02:45 MESZ schrieb Moritz Bergmann ***@***.***>:
>> Fascinating. For me the error disappeared after updating gboard!
>Thanks @mobergmann for your comment
>
>So you suggest its rather an issue with the keyboard and not the app?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/element-hq/element-x-android/issues/2682#issuecomment-2051344575
>You are receiving this because you commented.
>
>Message ID:
>***@***.***>

-- 
Martin Clauss
Meine Contactulater Card - All meine Kontaktinfo immer aktuell und vollständig:
https://contactulater.app/me/mc

**Comment by mobergmann** [comment]
I started digging and it seems, that the HeliBoard community is aware of the Issue. They have a corresponding thread/issue on their repository: [HeliBoard/#426](https://github.com/Helium314/HeliBoard/issues/426) (there are also the issues [HeliBoard/#664](https://github.com/Helium314/HeliBoard/issues/664) and [HeliBoard/#225](https://github.com/Helium314/HeliBoard/issues/225) which address the same problem). The issue is, likely, with the AOSP Keyboard from which HeliBoard, OpenBoard and GBoard are a fork of and GBoard fixed the issue, but didn't push the fix upstream (but that is just an assumption of some commentators).
[According to @‎ meichthys](https://github.com/Helium314/HeliBoard/issues/225#issuecomment-1879695798), the problem can be avoided by turning off Auto-Correction (whether you want to make the trade is up to you).

**Comment by maakuth** [comment]
I think this is not likely to be a keyboard issue, as I've only witnessed it with Element X and it happens on multiplex different keyboards (SwiftKey included). It started to happen a week ago or so.

**Comment by mobergmann** [comment]
It seems as this issue is gone. I can use Auto correction in Element x with heliboard again. Can someone else confirm this?

**Comment by mrclauss** [comment]
Yes, works here too...

Am 22. Mai 2024 14:24:48 MESZ schrieb Moritz Bergmann ***@***.***>:
>It seems as this issue is gone. I can use Auto correction in Element x
>with heliboard again. Can someone else confirm this?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/element-hq/element-x-android/issues/2682#issuecomment-2124664298
>You are receiving this because you commented.
>
>Message ID:
>***@***.***>

-- 
Martin Clauss
Meine Contactulater Card - All meine Kontaktinfo immer aktuell und vollständig:
https://contactulater.app/me/mc

**Comment by bmarty** [comment]
The issue seems to be fixed according to several comments here. Thanks!
