### ISSUE TITLE
Message context menu overlaps Screen lock pin

### ISSUE THREAD

**Issue by VolkerJunginger** [element-hq/element-x-android#2692]
### Steps to reproduce

Have EX installed and screen lock activated.
- Open a conversation.
- Go to a message an long tap to open the context menue (like, forward ...)
- Put app to background
- Bring app to foreground and try to log in.
--> The context menue is still visible and overlaps the pin code screen

![image](https://github.com/element-hq/element-x-android/assets/118339066/681cec2f-7512-42a4-9f9b-2916f6efe66f)

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by ganfra** [comment]
@VolkerJunginger is it acceptable to just close the context menu in this case?

**Comment by VolkerJunginger** [comment]
yes, that's fine. It does not have to be persisted.
