### ISSUE TITLE
Push notifications decrypt messages even though device is not verified

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#2716]
### Steps to reproduce

1. Update EX
2. Be faced by a request with device verification
3. Don't act on it but let it sit
4. Go elsewhere
5. Get a push notification

#### What did you expect?
Push notification cannot be decrypted

#### What happened instead?
Push notification is decrypted

![Screenshot_20240416-151101](https://github.com/element-hq/element-x-android/assets/640121/39f35cad-6308-4fb9-b506-8895939b9c37)

### Your phone model

Pixel 5

### Operating system version

Android 14

### Application version and app store

0.4.10-nightly

### Homeserver

element.io

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bnjbvr** [comment]
Not sure that's a bug; any new device will be known to other users' devices, and as such when they'll send new encrypted events, it'll be encrypted and sent to the new device, independently of verification (unless the other users have decided to not send encrypted events to untrusted devices — this setting is opt-in and off by default).

**Comment by claell** [comment]
Also see #2718 which also mentions this.

First, have you had verified the session, before updating the app? Possibly, the verification screen shows without need (meaning after the update, you were still verified despite the verification screen showing).

**Comment by kongo09** [comment]
I was verified before, then updated the app and then was asked to verify again with no way to bypass. @pmaier1 says this should only ever happen once so maybe this effect is a non issue?

**Comment by manuroe** [comment]
Messages decryption keys are still sent to unverified sessions. This feature is not implemented yet.

In https://github.com/element-hq/element-x-android/issues/2718, there is a race condition bug where the app badly shows the verification screen but your session is actually still verified.

**Comment by pmaier1** [comment]
This is not a bug. We're historically also sending new decryption keys to unverified devices. This will only change once we have implemented the isolation of unverified devices as part of [trust & decorations](https://github.com/element-hq/element-meta/blob/develop/docs/crypto/trust_v2.md).
