### ISSUE TITLE
[Task] Reset Recovery Key Screen

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-android#2740]
Please see and discuss the details in the meta issue.

**Comment by jmartinesp** [comment]
I believe this was already done in https://github.com/element-hq/element-x-android/pull/2657.

**Comment by bmarty** [comment]
Maybe this is not visible enough since I believe that the reset option is displayed only if the session is the last session?

**Comment by jmartinesp** [comment]
Oh, true. It seems like the designs changed and it's now always available. I'll get to it.

**Comment by claell** [comment]
> Please see and discuss the details in the meta issue.

Can you please link that one, so it can be found easily?
