### ISSUE TITLE
Allow notification distibutor change

### ISSUE THREAD

**Issue by BigPebble123** [element-hq/element-x-android#2763]
#### What would you like to do?
When I turn on the app for the first time and have Google services installed, Firebase will be selected by default. I would like to manually change the distributor to the ntfy app, but that is not possible.

#### Why would you like to do it?
n/a

#### How would you like to achieve it?
n/a

### Have you considered any alternatives?

Uninstalling Google services, I guess?

### Additional context

n/a

### Are you willing to provide a PR?

No

**Comment by spaetz** [comment]
https://github.com/element-hq/element-x-android/issues/2340

**Comment by jmartinesp** [comment]
Closing this issue as duplicate, thanks @spaetz .
