### ISSUE TITLE
Messages remain a very long time in state "Waiting for this message" (ie. waiting for decryption key)

### ISSUE THREAD

**Issue by Ezwen** [element-hq/element-x-android#2788]
### Steps to reproduce

1. Receive one or multiple messages in a room with E2E enabled
2. Open the room where messages are received

#### What did you expect?

- Either messages are shown, already decrypted,
- Or, messages are shown in the state "Waiting for this message" (ie. waiting for decryption key) for a short amount of time, before being decrypted.

#### What happened instead?

Messages remain in the state "Waiting for this message" (ie. waiting for decryption key) for a very long time (hours, days sometimes), until they somehow eventually end up decrypted.

**Note 1**:  that this problem does not appear with my regular Element app, which decrypts everything instantly.

**Note 2**: I self-administer the synapse homeserver I use, including the sliding sync proxy. Maybe I did something wrong in my setup, but everything works fine otherwise, and messages do eventually get decrypted? I cannot see any errors anywhere in logs.

### Your phone model

Xiaomi mi mix 2

### Operating system version

Lineage 21 (Android 14)

### Application version and app store

0.4.9, play store

### Homeserver

A server that I administrate, but I would prefer to not share it here. I can share info in DM though.

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
The message "Waiting for this message" will not appear anymore if this is a membership issue, because in this case the message will never be decrypted. In this case `You don't have access to this message` will be displayed instead. This should reduce the occurrence of this issue.
This has been implemented in https://github.com/element-hq/element-x-android/pull/2754.
