### ISSUE TITLE
Add support for spoilers

### ISSUE THREAD

**Issue by Cadair** [element-hq/element-x-android#2859]
#### What would you like to do?

[Spoiler Messages](https://spec.matrix.org/v1.10/client-server-api/#spoiler-messages) should be hidden from view in the timeline without some interaction and should not be shown in the content of push notifications.

#### Why would you like to do it?

So that I don't get F1 race results spoiled.

### Are you willing to provide a PR?

No

**Comment by Cadair** [comment]
(I am not sure if this is the right repo for this, feel free to move it to the relevant place.)

**Comment by ara4n** [comment]
dup https://github.com/element-hq/element-meta/issues/2424
