### ISSUE TITLE
[Task] Redesign sending state and remove Retry option for sending messages

### ISSUE THREAD

**Issue by Velin92** [element-hq/element-x-android#2863]
From element-x-ios created by [Velin92](https://github.com/Velin92): element-hq/element-x-ios#2842  

Please see and discuss the details in the meta issue.
Since the queue will now be handled automatically, also the Resend option will be redundant and we may actually remove it.

**Comment by spaetz** [comment]
MR #3011 includes this: `remove manual retry options, and fail sending state in the UI (this will be back soon..)`

So, I think this one can be closed as fixed-by #3011 ?

**Comment by ganfra** [comment]
Done in #3011
