### ISSUE TITLE
"You invited %1$@" still shows a matrix id

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-android#2866]
### Steps to reproduce

This is a bug found by Hans while testing https://github.com/element-hq/element-meta/issues/2395.

1. Open DM you started
2. Expand the room changes
3. The app displays ""You invited @bob:matrix.org" instead of Bob

<img width="419" alt="image" src="https://github.com/element-hq/element-x-android/assets/8418515/6724c123-137f-4551-8f1c-bb6bc700b817">

#### What did you expect?
A display name instead of a matrix id like on EW:

<img width="318" alt="image" src="https://github.com/element-hq/element-x-ios/assets/8418515/cabf08df-a391-4079-a38b-399037f4c5f7">

The invite event has a `displayname` field: 
```json
{
  "content": {
    "displayname": "testiosr123",
    "is_direct": true,
    "membership": "invite"
  },
  "origin_server_ts": 1663321374100,
  "sender": "@Manu:matrix.org",
  "state_key": "@testiosr123:matrix.org",
  "type": "m.room.member",
  "unsigned": {
    "age": 52463967527
  },
  "event_id": "$ryCuR93bduTjs-u5CPZQPNPnZZK_AQtp2_4Ys2SUXxk",
  "room_id": "!hQMQdhNMYBzbNfRaKh:matrix.org"
}
```

**Comment by jmartinesp** [comment]
Added https://github.com/matrix-org/matrix-rust-sdk/pull/3428 as a first step to get the required display name.
