### ISSUE TITLE
Jumping to a message cannot be aborted

### ISSUE THREAD

**Issue by frebib** [element-hq/element-x-android#2876]
With slow/no connectivity, jumping to a message shows a spinner with no way to abort, other than kill the app or wait for the timeout

https://github.com/element-hq/element-x-android/assets/775104/629ce7c9-281b-4e2a-995a-838b36c5991c

I would expect that a press of the back button would cancel this

**Comment by ganfra** [comment]
Yes, we need to add this, will do soon.
