### ISSUE TITLE
Room history not loading

### ISSUE THREAD

**Issue by arthursinclair** [element-hq/element-x-android#2888]
While loading rooms in EX for Android, sometimes I will see all the way back to the creation of the room, while other times, I see back a day or two, while other times I see just the last message I received. This is with an account on the matrix.org HS.
I have submitted bug reports from EX per guidance that I have received.

**Comment by jmartinesp** [comment]
The app version in those rageshakes is quite old, and we reworked the whole timeline pagination since then. Is there a chance we could test this against the latest version?

**Comment by bmarty** [comment]
Feel free to re-open if you see the same issue using the last version.

**Comment by manuroe** [comment]
https://github.com/element-hq/element-x-android/pull/2991 merged yesterday is probably the fix for this issue.
