### ISSUE TITLE
stuck notification with bad internet 

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-x-android#2906]
### Steps to reproduce

1. Send messages during bad internet 

#### What did you expect?
Not stuck notif
#### What happened instead?
Stuck notif

### Operating system version

android 13 based

### Application version and app store

schildichat next based on 0.4.13

### Homeserver

1.106.0, sliding sync 0.99.16

### Will you send logs?

Can't because Schildi

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Closing because not detailed enough.
