### ISSUE TITLE
Move Push provider settings to the notification settings

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#2912]
We added a way to change the push provider in #2873 . The setting has been added to the `Advanced settings` screen since it's quite an advanced setting indeed.

It's also having sense to have it to the `Notification` settings screen, but we did not want to annoy regular users with this power user setting.

Maybe another solution which will check the 2 requirements would be to move the setting to the `Notifications` setting screen, in an new `Advanced` section, but only displayed if several push providers are detected. With this solution:

- Gplay user with only Firebase will not see this setting
- Gplay users with a UnifiedPush provider installed (such as `ntfy`) can be considered as power users, since they have installed an alternative PushProvider and so will see the setting in the `Notifications` setting screen. 
- FDroid users will not have Firebase support, but will need to install a UnifiedPush provider. The `Notifications` setting screen may be a place to alert the user that no PushProvider is installed if this is the case. We are already alerting if Notification permission is not granted (see the screenshot below).

|Only one Push provider detected|Several push providers detected|
|-|-|
|<img width="323" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/76b451fe-d068-4e5a-b8cc-062232988f80">|<img width="325" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/8a9796e9-cccf-46c7-80e8-55d3c8bd92f2">|

**Comment by bmarty** [comment]
(Approved internally by @amshakal)

**Comment by damnms** [comment]
I am running 0.7.5 - i dont have this advanced feature, even if i turn on dev options. Where can i configure the push provider?
