### ISSUE TITLE
No ringing sound when receiving a call from Element Call

### ISSUE THREAD

**Issue by rajil** [element-hq/element-x-android#2915]
### Steps to reproduce

1. Where are you starting? What can you see?
Specify a custom Element Call base URL (self hosted Element Call)
2. What do you click?
Use the Camera button to call a remote user.  Element call opens up and the local user joins the call

#### What did you expect?
Remote receiver should have their phone buzz to indicate incoming call
#### What happened instead?
No notification appeared on the remote callers phone. However, the camera icon says 'Join'.

### Your phone model

S23

### Operating system version

Android 14

### Application version and app store

0.4.140 nightly, develop (544d0647)

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by manuroe** [comment]
Dup. The implementation of this feature is happening in https://github.com/element-hq/element-meta/issues/2385
