### ISSUE TITLE
Stuck unread marker on all chats

### ISSUE THREAD

**Issue by piegamesde** [element-hq/element-x-android#2920]
### Steps to reproduce

Not sure how to reproduce, it just happens to be like this for me

### Outcome

All chats are shown with an unread marker, with no way to get rid of it. Neither reading the chat nor "mark as read" work.

### Your phone model

Google Pixel 4

### Operating system version

LineageOS, Android 13

### Application version and app store

0.4.13 from GitHub releases

### Homeserver

conduwuit 0.3.4

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by frebib** [comment]
This is a condu(wu)it sliding sync implementation bug. Given that sliding sync is still in development, bugs are to be expected.

**Comment by Anutrix** [comment]
Still facing this issue.
