### ISSUE TITLE
ability to pin a message in a room

### ISSUE THREAD

**Issue by iamtalhaasghar** [element-hq/element-x-android#2937]
#### What would you like to do?
I would like to pin a message in a room. For example: important announcements.

#### Why would you like to do it?
Pinning a message ensures that important information or announcements remain visible at the top of the conversation thread, making it easily accessible to all members of the room.

#### How would you like to achieve it?
This would be similar to whatsapp pin msg functionality.

### Are you willing to provide a PR?

No

**Comment by ganfra** [comment]
Pinned messages is available now.
