### ISSUE TITLE
Can we not rely on Google play services?

### ISSUE THREAD

**Issue by mackerel225** [element-hq/element-x-android#2980]
#### What would you like to do?
Original element for Android relies on google play services for things like notifications. I would like us to implement our own solution for this, similar to Signal

#### Why would you like to do it?
Privacy

#### How would you like to achieve it?
With pull requests

### Are you willing to provide a PR?

No

**Comment by licaon-kter** [comment]
/close as duplicate https://github.com/element-hq/element-x-android/issues/1418

Signal uses websockets to their own closed sourced server

You want Element to connect where?

Anyway, the F-Droid version uses Unified Push so you can use any provider.
