### ISSUE TITLE
Login via QR code may not work on self-hosted server.

### ISSUE THREAD

**Issue by YamatoRyou** [element-hq/element-x-android#2998]
### Steps to reproduce

1. Install a recent nightly build;
2. Display the QR code from Element-Web or the desktop version;
3. Scan the QR code displayed in step 2 using the client installed in step 1.

#### What did you expect?
For self-hosted server, you should be able to successfully log in to the account corresponding to the QR code and complete session verification.

#### What happened instead?
As shown in the picture, the client returns an error that is unclear to the user.
![{4BD8B24D-F2D3-32B9-2BF5-AA0574D22696}](https://github.com/element-hq/element-x-android/assets/48104960/16abd21f-8933-476c-a8ce-ecdd6ee19988)

**Since the traditional version of Element also uses QR code login, the server also installs `matrix-http-rendezvous-synapse 0.1.12` to enable Synapse to support this feature.**
**Since the test uses the nightly build, I am not sure whether the QR code login feature is ready.**

Element desktop client version is 1.11.68 (x64 Windows)

### Your phone model

OnePlus MT2110

### Operating system version

Lineage OS (Android 14)

### Application version and app store

Element X Android 0.4.15 nightly

### Homeserver

Synapse 1.108.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Can you add a screenshot of the same screen in English please?

**Comment by YamatoRyou** [comment]
> Can you add a screenshot of the same screen in English please?

Yes, but I think it is meaningless at this point. Because I spent some time researching after submitting this article, this problem may be related to server support (MSC4108). The QR code scanned by the client is only applicable to the legacy branch, not the current branch. This eventually leads to the error shown in the figure. I have not yet found a complete operation process to enable the server to support this function.
![Uploading {D168AC38-3646-2AB2-2E6C-CFBE5555375D}.png…]()
