### ISSUE TITLE
i got logout every day

### ISSUE THREAD

**Issue by wrenix** [element-hq/element-x-android#2999]
### Steps to reproduce

1. login (in a setup with sliding sync, synapse and mas for oidc)
2. lock phone for a few hours

#### What did you expect?
use it till i press on any device logout for that session/device

#### What happened instead?
I open (in next day) element-x and i have to relogin.

(With element-web i do not have this problem)

### Operating system version

14

### Application version and app store

Release apk from github for fdroid v0.4.14 (this bug was also already in v0.4.13)

### Homeserver

Synapse 1.101.0, 

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by benparsons** [comment]
I also get logged out frequently, though not every day. I'll start sending logs

**Comment by wrenix** [comment]
Logs are send this time with a link to this issue.

---

I switch back to fluffychat (that works with MAS and sliding-sync).

Normal Element does not work with MAS: https://areweoidcyet.com/

**Comment by bmarty** [comment]
> 2024-06-14T19:54:40.098556Z ERROR matrix_sdk::client::futures: Token refresh: OIDC refresh_token rejected with invalid grant | crates/matrix-sdk/src/client/futures.rs:146

@sandhose can you help to understand this error please?

**Comment by bmarty** [comment]
Related: https://github.com/element-hq/element-x-android/issues/3028

**Comment by bmarty** [comment]
Fixed by #3050

**Comment by wrenix** [comment]
Works again, yes - thx
