### ISSUE TITLE
Reset the encryption instructions contain garbage placeholder characters

### ISSUE THREAD

**Issue by foresto** [element-hq/element-x-android#3041]
### Steps to reproduce

1. Launch Element X for the first time
2. Try to skip the device verification
3. Choose the encryption reset option
4. Read the instructions that appear on screen

#### What did you expect?

Clear instructions

#### What happened instead?

Step 3 instructs me to "select %1$s".

![select%1$s](https://github.com/element-hq/element-x-android/assets/322134/e833b7d1-462b-4950-9f02-9f8d059ed864)

### Operating system version

Android 10 (LineageOS 17.1)

### Application version and app store

Element X 0.4.14 F-Droid

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks, this has been fixed [here](https://github.com/element-hq/element-x-android/commit/30a1367714f5f43422cc364c5cb7165a359bf739#diff-f81cc3997920388b1791cd82353b800c331c31dd14d99dd812162c8e143710e8R73-R76) (sadly not in a dedicated commit), and this will render like this in the next release:

<img width="407" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/0c9e6afc-2815-433a-a35e-7f1831779739">
