### ISSUE TITLE
In the room timeline topbar, clicking on the room avatar has no effect

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#3063]
- open a room
- try to click on the room avatar. It should open the room settings
- click on the room name: it open the room settings

Clicking on the room avatar should also open the room settings to increase accessibility.

Also the click effect could be improved, currently this is a rectangle, could have a better shape with round corner.

![Toolbar](https://github.com/element-hq/element-x-android/assets/3940906/dbbabdf1-d070-420b-93f6-e083de020246)

**Comment by spaetz** [comment]
Interesting. On EXA 0.4.14 and Android 13, clicking on a room avatar does work for me. It opens the room settings. Just FYI, making the animations prettier is always good ;-).
