### ISSUE TITLE
No error indication if sliding sync proxy is down

### ISSUE THREAD

**Issue by inducer** [element-hq/element-x-android#3070]
### Steps to reproduce

1. Set up sliding sync, :tada: 
2. Stop sliding sync proxy (but keep underlying synapse running)
3. Observe that Element X appears happy, there is no "unable to connect to server" (or so) indication to show that an issue exists

#### What did you expect?

An error indication.

#### What happened instead?

None such

### Your phone model

Pixel 5a

### Operating system version

LineageOS 21

### Application version and app store

Element X 0.4.14 (F-Droid)

### Homeserver

Syapse 1.109

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks for reporting.

There is a plan to stop using the sliding sync proxy and directly use a client server API, so I do not think we will spend time to work on sliding sync configuration issue / down server, sorry.
