### ISSUE TITLE
Direct chats that use unencrypted rooms are not considered "direct" (despite them being marked as "People" and a DM in EW)

### ISSUE THREAD

**Issue by frebib** [element-hq/element-x-android#3071]
### Steps to reproduce

1. Create an unencrypted DM chat with another (single) user
2. Open the room details screen in EXA
3. Observe that it renders as if the room is a multi-person room, not a DM

#### What did you expect?
Unencrypted DM chats to be treated as DMs, just the same as encrypted ones are

#### What happened instead?
Unencrypted DMs are treated as regular rooms

Cause -> https://github.com/element-hq/element-x-android/commit/23a7b871f73dc919f289b18a3e9bfedfe20cd3f4#diff-461c4c5471a38079a9d3ddf1815da449c86ad98891f20052c9df7f596ba31b03R51

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by johansmitsnl** [comment]
This is a confirmed issue. Just tested this and switching to an encrypted room it works.

On iOS it works fine only Android it doesn't.

**Comment by spaetz** [comment]
Besides inconsistency, this had a very serious side effect:
When calling between EXA and EXI, it will ring on the Apple side, but not on the Android side. As call ringing will only happen in direct rooms. So in unencrypted rooms, calls will never ring (as they are not considered direct).
