### ISSUE TITLE
QR code login flow doesn't match Element Desktop

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#3091]
### Steps to reproduce

1. On EXA, I select: Sign in with QR code
2. The following screen asks me to go to a desktop device, click on my avatar and select "Link new device"

#### What did you expect?
When I go to Element Desktop and click on my avatar, I'm expecting an option saying "Link new device"

#### What happened instead?
No such option exists

![image](https://github.com/element-hq/element-x-android/assets/640121/aac75c5c-2b4f-4adf-aaf4-856787d50ad9)

### Your phone model

Pixel 5

### Operating system version

Android 14

### Application version and app store

0.4.16-nightly (40004160)

### Homeserver

element.io

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by jmartinesp** [comment]
That option *does* exist, but only on the nightly version of Element web/desktop for now:

<img width="315" alt="image" src="https://github.com/element-hq/element-x-android/assets/480955/a4ef76c8-5bfb-45ad-9088-4cba2e057011">

**Comment by jmartinesp** [comment]
In release builds of EXA, QR code login is disabled. It's only enabled on nightly and debug versions.

**Comment by pmaier1** [comment]
QR code login requires a backend with MAS. As this isn't yet widespread, the QR code login isn't yet a production feature in EX apps nor have we done the last steps in Web to support it.

There is a consistent design and all the preparations have been made. The MAS dependency needs to be resolved first, then we can take the next steps and bring everything together.

**Comment by kongo09** [comment]
> In release builds of EXA, QR code login is disabled. It's only enabled on nightly and debug versions for early testing:

Ok, thanks. That was not well-informed on my side. Apologies.
