### ISSUE TITLE
After opening multiple notifications, going back from room view does not navigate to rooms list view

### ISSUE THREAD

**Issue by nathanael-h** [element-hq/element-x-android#3098]
### Steps to reproduce

1. Ensure you received multiple notifications for different rooms
2. Open notification for room1
3. Room1 is opened
4. Open notification for room2
5. Room2 is opened
6. Open notification for room3
7. Room3 is opened
8. Touch back arrow on top left
9. App navigate from room3 to room2 
10. Touch back arrow
11. App navigate from room2 to room1
12. Touch back arrow
13. App navigate from room1 to room list view

#### What did you expect?
I expected that the back arrow navigate directly to the room list view
#### What happened instead?
It seems that opening a room notification push the room view on the navigation stack and that the back arrow simply pop the latest view from the navigation stack
I think that opening a room notification should clear the navigation stack before pushing a new view on it. 

### Your phone model

Fairphone 3+ 

### Operating system version

Android 13, /e/OS 2.1

### Application version and app store

Element X Android 0.4.14

### Homeserver

matrix.isidorus.fr / yunohost / synapse version 1.109.0 / sliding sync v0.99.18

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by frebib** [comment]
In the very least, if a room is in the backstack more than once, I would expect that the most recent copy of that room would remain open (especially now that we have draft support) but the older duplicates would be removed, otherwise you could end up revisiting the same room many many times trying to get out of the backstack from a ton of notifications

**Comment by nathanael-h** [comment]
Hello, I kindly share with you that this annoying issue drove me to test another Matrix client and finally use it daily (Fluffychat). Don't get me wrong, I share with you this end-user feedback so that you and the product and UX team can use it. I do not want to pressure. 

To explain more what is annoying: after a few hours away from phone (and also from any other matrix client), I might have messages in multiple matrix rooms (6 for example), with many new notifications. I open notification one after another. And at the end when I want to get back to the rooms list, I need to hit back arrow as many times as I got notifications (at least 6, sometimes more).

**Comment by atomdmac** [comment]
@bmarty  What are the cons to implementing this change?  What the use cases where the current behavior is desirable?

**Comment by titulebolide** [comment]
I really do agree with @nathanael-h. After a long time opening successively many notifications, this is quite surprising having to go back several time.
I think this would also be consistent with the UX of other messaging app.

**Comment by 0verEngineer** [comment]
No other messaging app does this, i don't get what the cons are in fixing this. This is simply broken UX.

**Comment by Destinyg133** [comment]
I dont understand what would cons be of fixing this. Id also agree its broken UX.
