### ISSUE TITLE
Drafts are not saved when room is open/animating back to timeline when app is killed 

### ISSUE THREAD

**Issue by frebib** [element-hq/element-x-android#3112]
### Steps to reproduce

1. Type a message into a room, but don't send it
2. (optionally navigate back to the room list, then quickly) terminate the app from the switcher
3. Re-open the app and observe that the draft is gone

#### What did you expect?
The draft to be saved, even if the room wasn't closed

#### What happened instead?
The draft was lost

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by manuroe** [comment]
What app version are you using? Is it nightly or the play store version?
I am considering it the play store version and a duplicate of https://github.com/element-hq/element-x-android/issues/2869

It will be available in the release candidate we build this week.

**Comment by frebib** [comment]
Sorry, I should have pasted a version. I'm building the app myself and it already contains all of the drafts implementation. This bug report is highlighting that it's inconsistent with saving drafts.

**Comment by frebib** [comment]
This still happens. Please re-open this issue
