### ISSUE TITLE
Calls don't use Themes (currently only light Theme)

### ISSUE THREAD

**Issue by DoM1niC** [element-hq/element-x-android#3135]
#### What would you like to do?
Theming from Element X native App Setting

#### Why would you like to do it?
We have light / dark Theme
### Are you willing to provide a PR?

No

**Comment by toger5** [comment]
This is supported by the rust widget driver and element call (Just tested it using the tauri widget wrapper)
```
widget_settings.generate_webview_url(&room, props)
// or kt
generateWebviewUrl(...)
```
Is where we can pass the theme as a string in props. So this could either be that android is passing null here or a more verbose string (only `dark` and `light` work currently (and i think their high contrast versions)).

Looking through the android code most of the things are hooked up so this probably needs someone debugging what is actually passed into `generateWebviewUrl`.

**Comment by bmarty** [comment]
Done in #3118 , will be in the next release.
