### ISSUE TITLE
Missing punctuation in advanced settings

### ISSUE THREAD

**Issue by everypizza1** [element-hq/element-x-android#3141]
### Steps to reproduce

1. Press profile picture from home
2. Press Advanced Settings
3. Notice how the last thing listed has no punctuation, unlike the rest of the settings

#### What did you expect?
The punctuation to be consistent
#### What happened instead?
Punctuation is not consistent

### Your phone model

OnePlus Nord N10 5G

### Operating system version

Android 11.0

### Application version and app store

0.4.15

### Homeserver

catgirl.cloud

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks, fixed in Localazy, will appear in the app during the next sync.
