### ISSUE TITLE
Element Call: Still not following the app theme.

### ISSUE THREAD

**Issue by YamatoRyou** [element-hq/element-x-android#3153]
### Steps to reproduce

1. Update to 0.4.16, then manually switch the color scheme to dark or depending on the system (if the system color scheme is already set to dark);
2. Enter a room;
3. Initiate a call driven by Element Call.

#### What did you expect?
n/a

#### What happened instead?
According to the 0.4.16 changelog, if the Element X theme is dark at this time, then Element Call should also be dark during display. However, it does not appear to do so.

As shown in the picture:
Dark mode is not enabled on the test device at this time, but Element X is manually configured for dark mode.
![Screenshot_20240706-125639](https://github.com/element-hq/element-x-android/assets/48104960/e9fc4cb5-eee4-4f29-b1b3-5062c5d43fa3)

--------
**Element Call is my self-hosted instance, version 0.5.17**
#3118 shows the screenshots I still see after updating to 0.4.16.

### Your phone model

OnePlus MT2110

### Operating system version

PixelOS (Android 14)

### Application version and app store

Element X for Android 0.4.16

### Homeserver

Synapse 1.110.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
You're right, there is a problem, and I have found the root cause. Will draft a PR.
