### ISSUE TITLE
Room joining doesn't work over federation

### ISSUE THREAD

**Issue by spaetz** [element-hq/element-x-android#3155]
#### What would you like to do?

I would like to be able to join rooms in EXA.

Also, I would like to be able to recommend EXA as a client to other people without having to answer that first question that always comes back from said users: 'installed it, so how do I join a room?' (answer 'use a different client 😳')

#### Why would you like to do it?

Being in the matrix without being in rooms is no fun. It is like going to Disney world but having to stay in the entrance area.

#### How would you like to achieve it?

Click matrix.to links, type /join #roomid, or whatever clever way you come up with.

Sorry for opening this super obvious ticket which you are well aware off, but I did not find any and I would like to follow the progress of this one.

### Have you considered any alternatives?

Carrying my ATX board desktop tower with me and use fractal. But it proved impractical.

### Are you willing to provide a PR?

No

**Comment by everypizza1** [comment]
You already are able to browse your homeserver's rooms with a toggle in developer options:
![Screenshot_20240707-071506](https://github.com/element-hq/element-x-android/assets/82726593/852dd43a-871d-4e59-bbf3-8517d862853f)
Clicking it will show a list of rooms on your homeserver, and you can join them.

**Comment by spaetz** [comment]
Given Mattew said, joining **should** be implemented, here is what I see.

1) a link to #dendrite:matrix.org only colors matrix.org blue and clicking it ends up on https://matrix.org

2) a /join command does not exist

3) a link to https://matrix.to/#/#dentrite:matrix.org opens EXA but simply displays a screen with (translated from German): `preview not available, you need to be a member to see messages in this room.`
  Heck, I **want** to become a member of the room, bit it does not offer me to join.

All in all, joining rooms seems pretty broken.

**Comment by frebib** [comment]
As @everypizza1 suggests, joining rooms published locally on the homeserver that are either open, or knock-to-join seem to work (via the room search, or a matrix.to link). Joining anything over federation doesn't seem to work

**Comment by ara4n** [comment]
it sound like the actual problem here might be that EXA depends on MSC3266 being enabled on the server?

**Comment by spaetz** [comment]
> it sound like the actual problem here might be that EXA depends on MSC3266 being enabled on the server?

Yes indeed, it seems to boil down to that, n eding MSC3266 enabled.
