### ISSUE TITLE
This server currently doesn’t support sliding sync.

### ISSUE THREAD

**Issue by XionghuiJi** [element-hq/element-x-android#3166]
### Steps to reproduce

When launching the app and switching the server address, a "This server currently doesn’t support sliding sync." popup appears. How can I disable the "Sliding sync" feature of the Android app?

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by YamatoRyou** [comment]
"Sliding Sync" is required for Element X. If the server does not support it, Element X cannot be used.

**Comment by bmarty** [comment]
In the future, there will be no need for a sliding sync proxy, but for now, as @YamatoRyou said, EX needs a proxy to work.

**Comment by kqvanity** [comment]
@bmarty
Where can one monitor this upcoming change?
