### ISSUE TITLE
Opening rooms is excruciatingly slow

### ISSUE THREAD

**Issue by frebib** [element-hq/element-x-android#3179]
This has been happening for a while now, but I've put up with it. It's getting to the point where the app is borderline unusable with how slow it is. Re-opening the app speeds up room opens to a reasonable rate (not even close to how fast WhatsApp is though, mind you) but after 2-3 times, it slows down again.

This video is real time and very representative of what it's like to use EXA for me

https://github.com/user-attachments/assets/f716ce47-00c5-447d-a1ee-71ff88624fb0

Yes, it really took ~7 seconds for that last room to open.

It seems to do this even when offline loading the "in memory cache" of the last few messages in the timeline, so it's probably not even a slow HS (not that my HS is often slow). I can even reproduce this to a slightly lesser extent with Element-X Nightly and a very fast conduwuit server with an account that only has about 10 rooms.

I haven't tried logging out and back in, but clearing the cache seems to do nothing. I can submit logs or even run custom patches to help debug, if required.

**Comment by DoM1niC** [comment]
same Problem here, have to swipe away to increase the perf
