### ISSUE TITLE
Filter pills display inconsistent

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#3190]
### Steps to reproduce

1. Observe room list
2. Filter for people 
3. Observe filter pills
4. Unselect the people filter and select the rooms filter
5. Observe filter pills

#### What did you expect?
When I filter for people, the pill for rooms disappears, which I expect, as there cannot be any room left to filter for once people is selected. The room filter this doesn't make sense and is removed. 

However, I still see the filter for unreads even though I don't have any unread DMs. I would expect that filter to disappear as well.

Now, when the filter for rooms is selected, the people pill rightfully disappears. But the pill for invites disappears as well, even though I have a room invite. I would have expected that invite filter to remain.

#### What happened instead?
Unread filter remains shown when people filter is selected and leads to an empty state if selected.

Invites filter is not shown when room filter is selected even though there is a room invite.

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ganfra** [comment]
All your remarks were products decisions and are excepted to be like that.

**Comment by kongo09** [comment]
@mxandreas please take a look at this product decision, ideally together with @amshakal . Maybe I miss something here, but from a user perspective, it doesn't feel right.

**Comment by mxandreas** [comment]
My take is that this is something that may be quite personal - e.g. may "not feel right" for one person but be fine for another. I think I would leave it as is until we get some more evidence how this is confusing for several users or impractical in certain situations.

I see two concise options:
a) Hiding the pills by excluding the situations that can never happen (e.g. something can not be a room and a person at the same time) - this seems to be the current logic.
b) Hiding the pills based on the current actual situation (e.g. hiding unread if you actually do not have any unread messages).

On top of that one could argue if "room" and "invite" to room are overlapping entities or not. It seems that current logic is that they are not, and I do not see anything immediately wrong with it.

**Comment by kongo09** [comment]
Happy to wait for more insights.

**Comment by bmarty** [comment]
FTR this is the meta story https://github.com/element-hq/element-meta/issues/2283

Closing the issue since no changes are needed right now on EXA.
