### ISSUE TITLE
[Task] Pinned items banner

### ISSUE THREAD

**Issue by Velin92** [element-hq/element-x-android#3213]
Please see and discuss the details in the meta issue.

A banner showing pinned items should be displayed at the top of the room if there is at least one pinned item.
It should display a preview of the body of the event, and tapping on it should scroll to the next pinned item if available, and go back to first pinned item if the last item was tapped.
Also a CTA allowing to "View All" pinned items should be present

**Comment by bmarty** [comment]
Done in #3275

**Comment by K4LCIFER** [comment]
This feature should be reverted, imo. That perpetual banner is just visual clutter. Pinned messages should just just be in a separate list that can be referenced. I see no benefit from perpetually showing one at the top. At the very least, it should be a toggleable option.
