### ISSUE TITLE
UTDs of recent history on fresh login

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-android#3234]
### Steps to reproduce

1. Log in on fresh EXA (today's 0.4.17-nightly)
2. Verify new login via emoji verif with ED
3. Observe recent message history is undecryptable. Older message history is okay.

This error is twinned with https://github.com/element-hq/element-x-ios/issues/3055 and https://github.com/element-hq/element-x-ios/issues/3045

#### What did you expect?

All history should be undecryptable.

#### What happened instead?

Recentish messages are undecryptable. Clearing cache however fixed this (although then the previously undecryptable messages still show as UTDs in the embedded replies, even though the msgs themselves now decrypt)

### Your phone model

Samsung S10

### Application version and app store

0.4.17-nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by richvdh** [comment]
Since this seems common to EXI and EXA, and likely a problem in the rust layer, I have pulled out a common issue to track fixing this in the rust layer: https://github.com/matrix-org/matrix-rust-sdk/issues/3768

**Comment by manuroe** [comment]
It was fixed some time ago in the SDK. We should have closed the issue at the same time as its iOS sister, https://github.com/element-hq/element-x-ios/issues/3055.

**Comment by richvdh** [comment]
Per https://github.com/matrix-org/matrix-rust-sdk/issues/3768#issuecomment-2550863993: fixed in https://github.com/element-hq/element-x-android/releases/tag/v0.6.0.
