### ISSUE TITLE
"Enter your recovery key" screen doesn't react after entering key

### ISSUE THREAD

**Issue by benparsons** [element-hq/element-x-android#3278]
#### What would you like to do?

After I enter a recovery key, and press "Continue", the button is grey and nothing else happens. It appears to have worked successfully but doesn't respond.

#### Why would you like to do it?

Confirm or deny that the key was accepted

#### How would you like to achieve it?

On success the app should redirect to the room list, or show a confirmation.

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
I alos observed this. This happen when the account was not verified before the verification was mandatory during the sign in process.

Now that the verification is mandatory, this should not be possible to be in this situation.

**Comment by xundeenergie** [comment]
> I just logged into 0.5.3 and the same situation happened for me.

Same here with 0.5.3

**Comment by johansmitsnl** [comment]
Can confirm that it happentto me with the `0.6.2` version to.

**Comment by kennu** [comment]
This happened to me when I installed Element X 0.6.3 today on Android.

How do I verify my Matrix account, if it being unverified causes this? How do I know if the account is verified or not?

There should be an error message letting the end-user know what is wrong, instead of the recovery key dialog just being stuck.

**Comment by kennu** [comment]
This still happens in 0.6.4. The app keeps asking for the recovery key, but entering it just results in the Continue button turning gray.
![Screenshot_2024-10-01-11-46-58-76_508fb70dcdbd51b3b84edd38d0498869](https://github.com/user-attachments/assets/38bb8f69-d0aa-4123-ad90-7abe991c0340)

**Comment by ptrne** [comment]
Yep, still happens with 0.7.0.

Also when manually navigating to the recovery UI via "Settings", it just returns to the settings UI and the red dot for "no recovery key set" is still active.

**Comment by foopub** [comment]
This has not been fixed. Observing same issue on 25.06.0

**Comment by BleepingCreepers** [comment]
Still not fixed as of October 11th, 2025

**Comment by nilchia** [comment]
I have the same problem.
version: 25.11.2
November 19th, 2025
Android version 16
