### ISSUE TITLE
 Device verification success screen appears after a fresh new registration #3126 

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-android#3279]
### Steps to reproduce

1. Select a HS with a MAS accepting registration (ask if you do not know one)
2. Create an account

<details>
<summary>The device verification success screen unexpectly appears</summary>
<img src="https://github.com/user-attachments/assets/0787482b-6a15-4237-a901-a4a93b27f717"/>
</details>

#### What did you expect?
Enteting within the app and seeing an empty room list.

#### What happened instead?
I had to hit to Continue instead

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by manuroe** [comment]
It is very similar as https://github.com/element-hq/element-x-ios/issues/3126 but less impactful. It is still a bad FTUE and we need to fix it.

**Comment by soshial** [comment]
I cannot enter the app because of this "Device verified" screen! When is this going to be fixed?
