### ISSUE TITLE
[Task] Remove the SS proxy waiting list

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-android#3293]
Please see and discuss the details in the meta issue.

**Comment by spaetz** [comment]
This has been fixed by https://github.com/element-hq/element-x-android/pull/3389 ?

**Comment by bmarty** [comment]
> This has been fixed by #3389 ?

No this is another screen, see "the screen to kill" in the related meta issue: https://github.com/element-hq/element-meta/issues/2498
