### ISSUE TITLE
Media failing to load

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-android#3296]
### Steps to reproduce

Various reports from #element-x-android:matrix.org that media doesn't always load. See rageshake(s)

#### What did you expect?

See media

#### What happened instead?

Get stuck on a blurhash

### Application version and app store

0.4.15

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Maybe related to https://github.com/matrix-org/matrix-rust-sdk/issues/3791.
I am investigating it.
