### ISSUE TITLE
Redacted messages continue to show in notification previews

### ISSUE THREAD

**Issue by Johennes** [element-hq/element-x-android#3310]
### Steps to reproduce

1. Send an image from another client
2. Receive the notification on Element X which shows the image
3. Redact the image on the other client
4. Notice how the notification on Element X still shows the image

Message with image redacted on Element Web:

![Screenshot 2024-08-20 at 09 15 32](https://github.com/user-attachments/assets/3cd0f2f0-b098-4deb-a2fe-5ad6d33be4d6)

Element X still showing the image in the notification:

![01fab203-0550-4228-a8ed-388fa3bc37d37530435372318880093](https://github.com/user-attachments/assets/0ef9e3d2-f515-4e44-a413-328e7a04e5cf)

This might seem fairly benign, however, last night there was a CSAM assault on one of the public Foundation rooms. Even hours after the attacker had been banned and their messages redacted, Element X on my phone still continued to present me the pornographic pictures in the unread notification.

#### What did you expect?

Redacted images should not show in notifications.

#### What happened instead?

They continued to show post redaction.

### Your phone model

Google Pixel 6

### Operating system version

14

### Application version and app store

0.5.0

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
Waiting for https://github.com/matrix-org/matrix-rust-sdk/issues/3859 to be handled.

**Comment by Johennes** [comment]
If this needs Rust support, it might be an issue on Element X iOS, too? I haven't tested this on iOS so far.
