### ISSUE TITLE
[PiP] Use new functions expose by Element Call about PiP

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#3326]
Element Call is exposing 3 new functions about PiP:

- `canEnterPip`: will return a boolean to let the application if it is possible to enter the PiP mode. If the call is in error state for instance, the application should not enter PiP but rather hang up the call. So if this function return `true`: enter PiP, else close the call.
- `enablePip` to be called when the Activity is entering PiP, and will let Element Call render the PiP mode correctly
- `disablePip` to be called when the Activity is exiting PiP, so render in fullscreen, and will let Element Call render the fullscreen mode correctly

Ref: https://github.com/element-hq/element-call/pull/2573

**Comment by pixlwave** [comment]
For your reference, this is how we're using the API on iOS:

https://github.com/element-hq/element-x-ios/blob/dad9618f59c7494dbc69c150f2d71856c1d97c00/ElementX/Sources/Screens/CallScreen/View/CallScreen.swift#L211-L259
