### ISSUE TITLE
Update SS room subscriptions even if the visible range doesn't change

### ISSUE THREAD

**Issue by stefanceriu** [element-hq/element-x-android#3379]
* we switched from range based subscribing with duplicate suppression to id based, but ids can change without ranges changing
* the all rooms list fetches at least 1 event per rooms and can cause rooms to come in and out of the visible range without user interaction

Related to https://github.com/element-hq/element-x-ios/issues/3088
Fixed on iOS in https://github.com/element-hq/element-x-ios/pull/3220

**Comment by jmartinesp** [comment]
I think there's nothing to do on Android for this one, when an item changes the visible range is updated and the new room ids are subscribed to, from what I saw in a quick test.
