### ISSUE TITLE
Key reset in EX shows unexpected "Create a new recovery key" option

### ISSUE THREAD

**Issue by jmartinesp** [element-hq/element-x-android#3403]
**[<img src="https://avatars.githubusercontent.com/u/21193500?s=17&v=4" width="17" height="17"> @pmaier1](https://github.com/pmaier1)** cloned issue [element-hq/element-meta#2521](https://github.com/element-hq/element-meta/issues/2521) on 2024-09-05: 

> At least on EXI (tested with 1.7.5), the key reset flow shows an unexpected "Create a new recovery key" option. This option doesn't give you the means to create a new recovery key (which isn't even possible at this point). Instead it just starts the regular key reset flow which is misleading and a duplication of the "Can't confirm" on the previous screen.
> 
> 
> 
> All in all, I think this is a leftover from previous designs and should be removed. Please check for Android as well.
> 
> 
> 
> ![IMG_8641](https://github.com/user-attachments/assets/81fc9068-0536-4881-a863-2c607c090c74)
> 
> 
> 
> @mxandreas @manuroe @stefanceriu @bmarty

**Comment by bmarty** [comment]
We do not have this button, you can see the screenshot here: https://element-hq.github.io/element-x-android/#SecureBackupEnterRecoveryKeyView

and the wording "Create a new recovery key" is not used in the Android project.
