### ISSUE TITLE
Rageshakes contain logs from other application installs

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-x-android#3405]
https://github.com/element-hq/element-x-android-rageshakes/issues/2619 seems to contain logs from two different versions of Element X. It would be much better if it only included the logs from the installation where the bug is being reported.

Potentially, this is a confidentiality violation: I might be happy to send rageshakes from, say, the dev version but not the prod version -- particularly if I am using different accounts for the two installs.

**Comment by richvdh** [comment]
This is bogus; the logs don't overlap. Sorry for the noise!

**Comment by bmarty** [comment]
To clarify:

The logs are coming from the same application, but with different versions, for instance:

- Application version: 0.4.16 (40004160) - release / gplay
- Application version: 0.4.12 (40004120) - release / gplay
- Application version: 0.5.0 (40005000) - release / gplay (with the new filenames)

but there are all from the release version of the application.

The debug version of the application uses a different appId, and this is the same for the nightly version. Each application cannot access logs of the others.
