### ISSUE TITLE
F-Droid isn't keeping up with releases

### ISSUE THREAD

**Issue by K4LCIFER** [element-hq/element-x-android#3431]
### Steps to reproduce

1. Go to Element X's app page on F-Droid
2. Observe that the most recent version available is v0.4.15.
3. Observe that, in this repo, the most recent version available is v0.5.2

#### What did you expect?

I would expect to download the most recent version of Element X on F-Droid

#### What happened instead?

I can only download, at most, v0.4.15

### Your phone model

N/A

### Operating system version

N/A

### Application version and app store

N/A

### Homeserver

N/A

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by K4LCIFER** [comment]
This might be a duplicate of https://github.com/element-hq/element-x-android/issues/3420.

**Comment by xundeenergie** [comment]
I use obtainium package-manager.
It grabs the apk directly from github and checks, if new releases arrived.

Because of f-droid doesn't give me the current versions.

**Comment by licaon-kter** [comment]
@xundeenergie ...because the app does not currently build in a reproducible way.

F-Droid would love to host the latest version, but verification fails.

**Comment by xundeenergie** [comment]
Ok.

But, if i want to use the latest release... i have to download it manually from github... obtainium will check and do this for me. :)

**Comment by K4LCIFER** [comment]
Why was this closed? Is it because it's a duplicate? Or is it resolved?

**Comment by licaon-kter** [comment]
It is resolved, 0.7.2 was just built and awaits the cycle to end and be published:

**Comment by K4LCIFER** [comment]
When is 0.7.2 expected to be in F-Droid? It's still stuck on 0.7.1.

**Comment by licaon-kter** [comment]
@K4LCIFER can you read my post again?

Then read: https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

**Comment by K4LCIFER** [comment]
Ah okay! Noted. My bad. 

Side note, is it possible to see the actual build output? I did a cursory look on GitLab, but I didn't find anything.

**Comment by licaon-kter** [comment]
@K4LCIFER use the monitor link as explained
