### ISSUE TITLE
Can not choose a notification target

### ISSUE THREAD

**Issue by xundeenergie** [element-hq/element-x-android#3448]
### Steps to reproduce

1. I run ntfy.sh as unified push notification service snd it worked until i upgraded to 0.5.3
2. Tried the test for notifications
3. Choose ntfy as notification provider
4. Run notification test

#### What did you expect?

Wirking notification via unified push.

#### What happened instead?

![IMG_20240912_073753](https://github.com/user-attachments/assets/cb827226-d69f-4688-b8f9-a6a047e8e59f)
![IMG_20240912_073815](https://github.com/user-attachments/assets/2784e872-25ee-4574-8aa3-c333cb6c94ab)

I can not choose ntfy in the dialog. It stays unset and the test fails.

![IMG_20240912_074908](https://github.com/user-attachments/assets/98be4809-fd3a-4bbc-94ed-ae902c83929d)

#Sidenote
Notifications work on the same phone for Elrment and Schildichat with the same provider.

### Your phone model

Google Pixel 7

### Operating system version

GrapheneOS Android 14

### Application version and app store

Element X v0.5.3 from Github

### Homeserver

Synapse (the latest from element-hq repo. Somrthing with 114 i think)

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by xundeenergie** [comment]
I've seen, notifications arrive from the test.
A

**Comment by xundeenergie** [comment]
Since 0.6.0 notifications are working again.
But i can not choose the notification service...

Is it, because i have only ntfy on my phone (graphrneOS)

**Comment by bmarty** [comment]
> Is it, because i have only ntfy on my phone (graphrneOS)

Yes, if there is only 1 push provider and there is no error, the application is hiding this setting.

Happy to see that the notification are working again for you. I guess we can close the issue?
