### ISSUE TITLE
Can't sign in via Authentik SSO, only username/password

### ISSUE THREAD

**Issue by alucryd** [element-hq/element-x-android#3452]
### Steps to reproduce

Open the app and search for my home server, which has sliding sync correctly set up, and a working SSO via Authentik

#### What did you expect?
I expected to see the Authentik button like with other clients

#### What happened instead?
I only see username and password fields, no SSO button

### Your phone model

Pixel 7a

### Operating system version

Android 15

### Application version and app store

Element X 0.5.0

### Homeserver

Synapse 1.113.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by SpeedyFireCyclone** [comment]
I'm encountering this issue as well, only password authentication is offered as a sign-in option.
If I disable password authentication in favor of only SSO, the app claims that it can not contact the home server, which is incorrect as I can see it hitting in the reverse proxy logs.

Pixel 7, Android 14
App version: Element X 0.6.1 -⚠️[debug build GDVpiV](https://webapp.diawi.com/install/GDVpiV) for #3458, to test native SS support.
Server version: Synapse 1.114.0

**Comment by SpeedyFireCyclone** [comment]
After configuring [MAS](https://github.com/element-hq/matrix-authentication-service/) instead of the legacy (Synapse native) OIDC implementation, logins with Authentik do work as expected.

**Comment by alucryd** [comment]
Thanks, stumbled upon mas later on and I forgot to get back to this issue. I have yet to set up mas, but it is indeed the solution. Closing.
