### ISSUE TITLE
[Task] SSS Migration: Force logout if the SS proxy is no more available

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-android#3456]
It is phase 3 of https://github.com/element-hq/element-meta/issues/2499. EXI has this force logout since https://github.com/element-hq/element-x-ios/pull/3252.

**Comment by manuroe** [comment]
@jmartinesp can we consider it was done in https://github.com/element-hq/element-x-android/pull/3458?

**Comment by jmartinesp** [comment]
Oh, I didn't realise this issue was around. Yes, it's fixed, we can close it.
