### ISSUE TITLE
Native sliding sync migration banner does not show up on an old session

### ISSUE THREAD

**Issue by tonkku107** [element-hq/element-x-android#3468]
### Steps to reproduce

1. Have an existing session from element x < 0.5.3, and before simplified sliding sync was enabled on synapse
2. Enable simplified sliding sync in synapse
3. Update to element x ≥ 0.5.3

#### What did you expect?
Migration banner added in 0.5.3 (#3429) to show up

#### What happened instead?
No banner appears

### Your phone model

Google Pixel 8

### Operating system version

Android 15

### Application version and app store

0.6.0 (Play Store)

### Homeserver

Synapse 1.114.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
You may need to wait a few days for the sdk to refresh the homeserver capabilities.

**Comment by tonkku107** [comment]
for the record, it's been a week

**Comment by tonkku107** [comment]
I just noticed the developer setting for simplified sliding sync is turned on even though the client is still using the sliding sync proxy. I didn't touch the setting on the stable play store version.

It's possible #3458 in 0.6.1 enabled it by default even on existing sessions before homeserver capabilities were refreshed which blocks the migration banner from ever showing up

**Comment by tonkku107** [comment]
Fixed in 0.6.5
