### ISSUE TITLE
Images not rendering properly nor opening

### ISSUE THREAD

**Issue by diogotavc** [element-hq/element-x-android#3483]
### Steps to reproduce

Just send an image in a private chat (haven't tested in a public chat room).

### Outcome

This will lead to a blurred preview and an error upon opening (the image shows up fine on other sessions of the same account and for the other person).

### Your phone model

Google Pixel 7a

### Operating system version

Android 14 (latest stable GrapheneOS)

### Application version and app store

Element X 0.4.15 (code 40004152) from F-Droid

### Homeserver

matrix.org

### Will you send logs?

No, but I can grab them if deemed necessary.

### Are you willing to provide a PR?

No

### Screenshots

<p float="left">
  <img src="https://github.com/user-attachments/assets/cf9afb24-ebfb-4557-a6ee-fe67e659c7e1" alt="Screenshot_20240917-233815" width="45%" />
  <img src="https://github.com/user-attachments/assets/e4148af2-c5f4-4a9d-8cf0-b1d7d43c3a0f" alt="Screenshot_20240917-233804" width="45%" />
</p>

**Comment by diogotavc** [comment]
Not sure I should grab logs for this bug, but I can if it's deemed necessary.

![Screenshot_20240917-233815](https://github.com/user-attachments/assets/cf9afb24-ebfb-4557-a6ee-fe67e659c7e1)
![Screenshot_20240917-233804](https://github.com/user-attachments/assets/e4148af2-c5f4-4a9d-8cf0-b1d7d43c3a0f)

**Comment by ganfra** [comment]
This version doesn't contain media authentication. If you can use google play version, update with it. Otherwise you'll have to wait until we can have a reproducible build again in fdroid.
