### ISSUE TITLE
Ability to add nickname client side for contacts

### ISSUE THREAD

**Issue by d8f6** [element-hq/element-x-android#3511]
#### What would you like to do?
Edit: After thinking about it, the first thing that is needed is an actual contact list. There really doesn't seem to be a way to save contacts at all. At least not any way a normal person would be able to figure out. Why is this not a fundamental feature of the program in the first place if the goal is to be a messenging application? Every time I want to delete a chat I have to search for their username assuming this is something I remeber? 

I would like to be able to save a name/nick of someone on the client instead of just seeing their username. In one-on-one conversations, I may not always know who I am chatting with if I do not remember their username. So, I would like to be able to display the contact on my end as something I define. Example: Mom, Friend_Name, etc... I would very much like to make this my go to messenger for chats. Okay, thanks. 

### Have you considered any alternatives?

I am unsure of whether or not there is an alternative way to do this?

### Are you willing to provide a PR?

No

**Comment by frebib** [comment]
This sounds perhaps like something for github.com/element-hq/element-meta, or maybe even an MSC?
Could perhaps use https://spec.matrix.org/v1.9/client-server-api/#get_matrixclientv3useruseridroomsroomidaccount_datatype

**Comment by d8f6** [comment]
Okay, made a request here: https://github.com/element-hq/element-meta/issues/2538

Going to close the thread here now.
