### ISSUE TITLE
Incorrectly states "You don't have any favourite chats"

### ISSUE THREAD

**Issue by benparsons** [element-hq/element-x-android#3521]
Can't view any favourite rooms.

![Screenshot_20240923_192904_Element X nightly](https://github.com/user-attachments/assets/17246b66-db79-4591-a4d8-d4bce4dee88b)

0.6.4 nightly

**Comment by benparsons** [comment]
Logs sent

**Comment by jmartinesp** [comment]
I think this is caused [by a native sliding sync bug](https://github.com/element-hq/synapse/pull/17707) that's fixed but not deployed yet in this HS.

**Comment by ganfra** [comment]
It's a SSS issue, it has been fixed but not yet deployed on element.io
