### ISSUE TITLE
Unopenable link

### ISSUE THREAD

**Issue by hary777** [element-hq/element-x-android#3529]
### Steps to reproduce

When I receive image with link in body, The link can not be clicked or even copied as a text.
The message is bridged from facebook.

Example message:
`{
  "age": 50088030,
  "content": {
    "body": "https://www.facebook.com/share/r/bCaYCvTDbMB2xqk8/",
    "external_url": "https://www.facebook.com/share/r/bCaYCvTDbMB2xqk8/",
    "fi.mau.meta.xma_fetch_status": "unsupported",
    "filename": "image.jpg",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"https://www.facebook.com/share/r/bCaYCvTDbMB2xqk8/\">https://www.facebook.com/share/r/bCaYCvTDbMB2xqk8/</a>",
    "info": {
      "h": 200,
      "mimetype": "image/jpeg",
      "size": 11427,
      "w": 200
    },
    "m.mentions": {},
    "msgtype": "m.image",
    "url": "<CENSORED>"
  },
  "event_id": "<CENSORED>",
  "origin_server_ts": 0,
  "room_id": "<CENSORED>",
  "sender": "<CENSORED>",
  "type": "m.room.message",
  "unsigned": {
    "age": 0,
    "membership": "join"
  },
  "user_id": "<CENSORED>"
}`

![image](https://github.com/user-attachments/assets/512ae217-7870-4b90-9f82-48e64c4c27f5)

#### What did you expect?
I can click on link which open in browser.
Or copy text and paste to browser address bar.

#### What happened instead?
Nothing

### Your phone model

Motorola g32

### Operating system version

Android 14

### Application version and app store

0.6.3

### Homeserver

Synapse 115

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by frebib** [comment]
You can reproduce this with any captioned image by simply clicking on the caption. It should do nothing, but instead it opens up the image

**Comment by hary777** [comment]
Still persist in v0.7.1

**Comment by jmartinesp** [comment]
It should be fixed via #3864.
