### ISSUE TITLE
Rageshake only contained 20 minutes of logs

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-x-android#3541]
... which was unhelpful.

https://github.com/element-hq/element-x-android-rageshakes/issues/2825

**Comment by richvdh** [comment]
Fix is https://github.com/element-hq/element-x-android/pull/3540 I think?

**Comment by richvdh** [comment]
@jmartinesp: do you know if this is now fixed?

**Comment by jmartinesp** [comment]
It should be.
