### ISSUE TITLE
Room topics not visible with SSS

### ISSUE THREAD

**Issue by spaetz** [element-hq/element-x-android#3557]
### Steps to reproduce

This is the digital twin of EXI: https://github.com/element-hq/element-x-ios/issues/3312, it is happening on Android EX 0.6.4 too.
Seems to be caused by Synapse, though: https://github.com/element-hq/synapse/issues/17698

### Outcome

no room topic visible, despite the room having a topic for months.

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks for creating the issue to track when it will be fixed in EXA! As you said, it will be fixed on Synapse.

**Comment by spaetz** [comment]
Room topics show in EXA 0.7.2, using synapse 1.118. closing this reminder.
