### ISSUE TITLE
Stop hiding notification provider setting

### ISSUE THREAD

**Issue by 0verEngineer** [element-hq/element-x-android#3558]
#### What would you like to do?
- change from firebase to unified push with ntfy

#### How would you like to achieve it?
- with the setting in 'Advanced Settings'

### Have you considered any alternatives?

No

### Additional context

https://github.com/element-hq/element-x-android/issues/3448 Here it is stated that the setting is hidden if there are no errors

### Are you willing to provide a PR?

No

**Comment by spaetz** [comment]
No, the setting is hidden if there is only a single Push provider, so there would be no choice anyway. If youbhave Firebase/GCM installed, and a UnifiedPush distributor, the setting will be there.

So, this issue is moot, I'd guess.

**Comment by 0verEngineer** [comment]
Ok thank you, you are correct i just installed ntfy on my tablet and the setting is there.
