### ISSUE TITLE
Trust & Decoration | Show specific decryption errors for messages sent from an insecure device. 

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-x-android#3624]
part of https://github.com/element-hq/crypto-internal/issues/308

When [OnlySignedDeviceIsolationMode](https://github.com/element-hq/element-x-android/blob/5a4e5d057551d0aabe280cb130bdc444e578dcba/libraries/featureflag/api/src/main/kotlin/io/element/android/libraries/featureflag/api/FeatureFlags.kt#L126) is enabled, messages sent from insecure devices will fail to decrypt.

Currently these messages will be displayed as regular UTD:
<img width="313" alt="image" src="https://github.com/user-attachments/assets/33442c69-d986-443f-9352-59735a1508d4">

Ultimatly these messages should be hidden in the timeline, but as a first step we need to display a specific UTD error
<img width="705" alt="image" src="https://github.com/user-attachments/assets/ff84ab0c-1d32-4ad6-9ca9-5af90ddfe307">

Here is the [design for push](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=443-12319&node-type=frame&t=Jj4mYFHcWHxSaV1u-0) for verified identity changes, for insecure device we should not show a notification?

<img width="307" alt="image" src="https://github.com/user-attachments/assets/59909352-3f5f-4428-a8b6-b853497350fb">

Depends on 
https://github.com/matrix-org/matrix-rust-sdk/issues/4048
https://github.com/element-hq/element-x-android/pull/3569

**Comment by mxandreas** [comment]
> Here is the [design for push](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=443-12319&node-type=frame&t=Jj4mYFHcWHxSaV1u-0) for verified identity changes, for insecure device we should not show a notification?

@BillCarsonFr I think the push notification is not relevant here, it was really meant for when the verified user changes their identity (after we decided we still want to keep showing the message).

For unverified devices, I think the notification can remain (if it is currently there) and would disappear once we decide not to show the messages anymore at all.
