### ISSUE TITLE
Ignore only m.direct room entry to non-existing room instead of ignoring all

### ISSUE THREAD

**Issue by spaetz** [element-hq/element-x-android#3659]
I suffered from an empty "Persons" tab ( (EXA 0.7). Examining the account m.direct data, the json validated just fine and it did NOT contain obvious non-sense such as "[object Object]" (see issue #3074), but it might have contained entries to rooms that do not exist any longer.
I emptied the `m.direct` data and repopulated it using EW and the `/converttodm` feature and now all people show correctly under the people's tab.

This issue is about making EXA (or the Rust SDK) simply ignoring invalid entries to rooms that do not exist rather than ignoring everything in case one of the entries seems invalid.

There is an additional task about whether synapse should clean up useless `m.direct` entries or whether EXA (Rust SDK?) should be doing the cleaning up? But that is an additional followup :-).

_Originally posted by @spaetz in https://github.com/element-hq/element-x-android/issues/3074#issuecomment-2406646464_

**Comment by bmarty** [comment]
Rooms must stay listed in `m.direct` even if the user leave them. In case user is invited again, the room still have to be seen as a DM.

Moving the issue to the Rust SDK project as I believe this is where the fix has to be located.

**Comment by spaetz** [comment]
OK,  experimented with my m.direct data, and added non-existing rooms and/or user names. And even after deleting the cache, EXA worked fine, showing all persons in the persons tab. So, I have to conclude that my m.direct json was somehow corrupted in subtle ways and will close this issue. Will reopen a new one in the Rust SDK if I ever re-encounter this. Sorry for the noise.
