### ISSUE TITLE
Bluetooth mic muted during call if the app is not in foreground and the screen is on

### ISSUE THREAD

**Issue by davidegirardi** [element-hq/element-x-android#3679]
### Steps to reproduce

When calling using a Bluetooth headset I must keep Element-X in foreground and keep the screen on. If I turn it off or background the app my mic goes silent.

### Outcome

The mic is muted as soon as the screen is off or the app is in background without picture in picture.

### Operating system version

Android 14

### Application version and app store

0.6.4

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks for creating the issue. We need to apply the same patch than on Element Android, which is currently being reviewed: https://github.com/element-hq/element-android/pull/8914
