### ISSUE TITLE
Sending media when there are unverified device fails without giving details about the issue.

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#3757]
1. Have a unverified device.
2. Try to send a text message
3. An alert is displayed if I click on the error on the message

<img width="395" alt="image" src="https://github.com/user-attachments/assets/0364b33f-8552-4820-aa4a-34388593066b">

4. Try to send an image
5. On error is displayed without more details

<img width="343" alt="image" src="https://github.com/user-attachments/assets/1651df5d-83c9-4260-9c03-e5afbc4c069f">

The logs are not helpful:

> org.matrix.rustcomponents.sdk.RoomException$FailedSendingAttachment: Failed sending attachment

CC @Hywan , maybe something to improve at the Rust level.

**Comment by manuroe** [comment]
I think you wanted to ping @bnjbvr 😛 .

We want to address this with local echo for media. See https://github.com/element-hq/element-internal/issues/433. It is listed as part of the user stories. We have not created the dedicated GH issue yet.

**Comment by bmarty** [comment]
I confirm that this issue is fixed with the Rust SDK 0.2.60. I can now send an image, which will fail but as per any other sent message:

<img width="401" alt="image" src="https://github.com/user-attachments/assets/1d8871e2-0fcc-45a1-bca3-db0f6b3934c6">

Well done @bnjbvr !
