### ISSUE TITLE
Authenticate new session of another client application

### ISSUE THREAD

**Issue by yookoala** [element-hq/element-x-android#3775]
#### What would you like to do?
When I login with a new client, an already login Element X should be able to authenticate the session login.

#### Why would you like to do it?
I do not want to keep installing both Element and Element X on my device. I am forced to do it (especially because I use unofficial desktop client that it cannot do session authentication).

#### How would you like to achieve it?
When I use a new client to login, it would ask me to use existing an client session to authenticate the new one. I would like to do the emoji or QR code check with an already login Element X.

### Have you considered any alternatives?

Yes, but it doesn't work if I want to only use Element X on my phone. I also don't think secret key (Or whatever it is called officially. The naming is so inconsistent for users) is a user friendly way to do session authentication.

### Additional context

I cannot find existing issue about this. Please let me know if this is duplicated l.

### Are you willing to provide a PR?

No

**Comment by tonkku107** [comment]
Already implemented in #3733 and will be available in the next release

**Comment by yookoala** [comment]
@tonkku107: Thanks. I'm closing this issue now.
