### ISSUE TITLE
Element call: give audio feedback while waiting

### ISSUE THREAD

**Issue by frandavid100** [element-hq/element-x-android#3849]
#### What would you like to do?

When I call someone through Element Call, I want to be able to tell when the other person has picked up without having to stare at the screen.

#### Why would you like to do it?

Because I want to be able to look elsewhere while I wait.

#### How would you like to achieve it?

I'd like Element X to behave like other apps: ring while you're waiting for someone to pick up, stop ringing (and maybe give some additional audio feedback) when someone picks up.

### Are you willing to provide a PR?

Yes

**Comment by rajil** [comment]
This is a duplicate of [this](https://github.com/element-hq/element-call/issues/926).

**Comment by frandavid100** [comment]
> This is a duplicate of [this](https://github.com/element-hq/element-call/issues/926).

They look like completely different issues to me.

**Comment by rajil** [comment]
[This](https://github.com/element-hq/element-call/issues/2720)?

**Comment by frandavid100** [comment]
> [This](https://github.com/element-hq/element-call/issues/2720)?

OK, now this is the same issue. Thanks!

**Comment by toger5** [comment]
Close as duplicate (see prev messages).
