### ISSUE TITLE
Send caption with file

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#3884]
Thanks to https://github.com/matrix-org/matrix-rust-sdk/pull/4273, it is now possible to set a caption when sending a file.

Consequently:
- [ ] the media preview must be used when sending a file, currently this step is skipped
- [ ] the caption may be sent along with the file
- [ ] the caption of the file must be rendered in the timeline
- [ ] the caption of the file must be rendered in the last message in the room list

**Comment by pixlwave** [comment]
@bmarty I'm closing this as I appears it was handled in https://github.com/element-hq/element-x-android/pull/3902 and it is the only remaining task in the epic, but obviously feel free to re-open if there is more to do on your side :)
