### ISSUE TITLE
Missing file extension when sending photos makes them show up as attachment on element-web

### ISSUE THREAD

**Issue by surakin** [element-hq/element-x-android#3894]
### Steps to reproduce

1. Where are you starting? What can you see?
Take a picture with the latest build and it shows up like this on element web
![image](https://github.com/user-attachments/assets/46ad37f5-1b88-473c-94ab-cd3d6ff2d89f)

I copied the event content and sent it with the devtools adding '.jpg' manually and it showed up correctly.

#### What did you expect?
Photos should be visible on element-web
#### What happened instead?
It only shows the filename

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by szimszon** [comment]
Confirmed.
