### ISSUE TITLE
Element Call links cause a "401" error modal and the call does not load

### ISSUE THREAD

**Issue by benparsons** [element-hq/element-x-android#3896]
### Steps to reproduce

1. click a link in Google Calendar to eg call.element.io/....
2. EXA opens
3. it previously would open the call, now it just gives a bare 401 error popup

1. in EXA, click a link to eg call.element.io/....
2. same popup appears

#### What did you expect?

This did previously work

#### What happened instead?

401 error

### Your phone model

Samsung S20 FE

### Operating system version

Android 13

### Application version and app store

0.7.4-nightly

### Homeserver

element.io

### Will you send logs?

Yes

NB logs sent include opening an external link from another, then opening the same link from inside a room

### Are you willing to provide a PR?

No

**Comment by benparsons** [comment]
![image](https://github.com/user-attachments/assets/526ad235-b5fe-4dbf-8d37-d90d3b424187)

**Comment by hughns** [comment]
The is a fix in progress in https://github.com/element-hq/element-x-android/pull/3962
