### ISSUE TITLE
Avatars for (some) DM's dont render

### ISSUE THREAD

**Issue by toger5** [element-hq/element-x-android#3911]
### Steps to reproduce

1. Where are you starting? What can you see?
in the room list. I see round placeholders for DM avatars
2. What do you click?
I click on the room, on the room header, and I see the room info page where the avatar is renderend (mine and the one form the opponent member)

#### What did you expect?
I expected the other persons avatar to render in the timeline already
#### What happened instead?
I saw the two initial letters preview with a random bg color.

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by frebib** [comment]
Similar to/same as #3581

**Comment by toger5** [comment]
Closing in favor of https://github.com/element-hq/element-x-android/issues/3581 (It has more details and the find that this is caused by a temp third user)
