### ISSUE TITLE
E2EE Backup isn't working, despite cross-signing

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-android#3923]
### Steps to reproduce

I (Matthew) received a report from a user:

> EX told me to log out and log in again. Now I can’t decrypt my old messages anymore. Can anyone help me? (I think I never used recovery keys. At least everywhe else I log in, key exchange works, so I never had to enter a recovery key).

where "key exchange" is cross signing.

> Key backup and cross signing always have been active. That worked for several years for me on different devices.

> I did verify. Now I logged out, deleted the session, logged in again with verification – and all I see in 1:1 chats are the emojis attached to encrypted “waiting for this message” messages. 😕

#### What did you expect?

Verifying the device should have set up backup, but empirically it hasn't.  (Perhaps backup was never actually set up, and everything has been operating based on key sharing?)

#### What happened instead?

User has UTDs everywhere after logging in on EX, after logging out.

### Your phone model

ONEPLUS A6013

### Operating system version

Android 11; lineage_fajita-userdebug 11

### Application version and app store

0.7.3

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by fbruetting** [comment]
I just checked 0.7.2 on another device using Android 15 (CalyxOS 6.1.0). Result is the same.

**Comment by BillCarsonFr** [comment]
As per logs this session is not getting the backup secret from gossiping.
It is doing the request and not receiving the response.

That means that the session you are verify against do not have the backup decryption key in cache.
That decryption key should be in the recovery, so entering the recovery key will help.

Other option is to verify against another sesssion that have the key in cache.


> At least everywhe else I log in, key exchange works,

Element-X is not requesting keys to other sessions anymore, you need a working backup

**Comment by BillCarsonFr** [comment]
Would help to have logs/rageshake from the device you are verifying against

**Comment by BillCarsonFr** [comment]
Maybe related? https://github.com/element-hq/element-web/issues/28349 
(This time there is a backup but it not trusted)

**Comment by fbruetting** [comment]
I just now sent in two „report a problem“ messages which I hope to be rage shakes. As the old “shaking rage shakes” don’t work in EX for me.

I hope that my Element-Online session still has the keys, because I can’t find my recovery key and I deleted most of my sessions lately. :/

**Comment by fbruetting** [comment]
OK, this is strange. I try to explain:

-  The session of app.element.io should be quite old, maybe two years I guess. This is the only session where I can read all my old messages. If this session is missing the key to the server-side message key storage (and you’re saying that old messages are thereby los) – is there no way to preserve my old messages?
- I thought the sessions implicitely share the decryption keys – at least I thought that’s what “cross-signing” is all about…? This is different from my experience in the past, where (aside from several decryption bugs) all my sessions always used to be able to restore old messages and decrypt them as soon as I activated cross-signing back in time when it was new.
- As mentioned at the end of post number two here, I tried this first on my OnePlus 6T and then re-checked on my Pixel 6 Pro (it’s correct that I tried with both app.element.io and Fractal). Both devices showed the same behaviour, which is described above.

**Comment by richvdh** [comment]
> * The session of app.element.io should be quite old, maybe two years I guess. This is the only session where I can read all my old messages. If this session is missing the key to the server-side message key storage 

Could you share a screenshot of the "Secure Backup" panel in the "Security & Privacy" settings (with the "Advanced" tab open)? I've *assumed* it doesn't have access to key backup (aka server-side message key storage) based on the fact it didn't send the key backup key to your new device, but it would be good to confirm that.

> (and you’re saying that old messages are thereby lost) 

That depends what you mean by "old". If your session does not have access to the key backup, then that session will be unable to fetch keys to messages that *it doesn't already have*. If your session has been running for two years, it should already have the keys to at least messages sent within those two years, so they are not lost.

> – is there no way to preserve my old messages which are currently still decryptable and readable?

If the messages are decryptable and readable, then your Element Web must have the keys to those messages. Once you reset key backup, Element Web will upload those existing keys to the *new* key backup. So those messages will be preserved.

> * I thought the sessions implicitely share the decryption keys – at least I thought that’s what “cross-signing” is all about…?

Sessions used to share message keys between each other, but we found that introduced more problems than it solved, and it was disabled (https://github.com/element-hq/element-web/issues/26524). Instead, we rely on key backup: your existing sessions should upload message keys to key backup; then, when you log in a new device and verify it, it can fetch the keys from key backup.

Cross-signing serves a number of purposes; in this case, it indicates to your other devices that your new device is genuine and it is therefore safe to share the key-backup-key with the new device.

> This is different from my experience in the past, where (aside from several decryption bugs) all my sessions always used to be able to restore old messages and decrypt them as soon as I activated cross-signing back in time when it was new.

This should still be the case, provided key backup is working correctly.

**Comment by richvdh** [comment]
@fbruetting I'm going to go ahead and close this. Let us know if you have any more problems.
