### ISSUE TITLE
Add transition for users entering and leaving space.

### ISSUE THREAD

**Issue by Alpha-Julia** [element-hq/element-x-android#3925]
#### What would you like to do?
I want a transition into the spaces and out of the spaces to provide a user a clear feeling that they are on a new page that contains the space's contents. When users click on the space, the transition plays. When the user hits the back button the transition plays in reverse. 

#### Why would you like to do it?
I worked with a couple of users testing the app's interface for practice with usability studies. A commonality was having difficulty understanding where they were within the app when inside spaces they organized and when they were on the main page. 
The main page has the same feel as the spaces, and the current transition is a very fast fade that feels like a filter being applied rather than a space. I think this would give the feeling of movement for a mental model and lean into the used terminology like space.

#### How would you like to achieve it?
A quick transition like an individual wave from a water droplet. No ripple but a transition coming from the space button. 

A close example of the concept, this would be as the space is exited. This transition in reverse would be the entering animation.

https://github.com/user-attachments/assets/7151e016-efd5-4f14-ba93-33efc5a6c925

### Have you considered any alternatives?

My alternate consideration was an issue focused on more customization options that allow for colorization of the space, or letting the backgrounds be set to an image possibly. These can be alternate indicators that the user is in a space. 

### Additional context

My background has been academic in my research on the app as I am a student in an OSS class, I'm not sure I have the skillset to implement my enhancement request. 

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
EX does not support Space yet. Is this issue for https://github.com/element-hq/element-android/ instead?

**Comment by Alpha-Julia** [comment]
OH! It is, my mistake
