### ISSUE TITLE
Georgian Language - State Fire Service of Poland

### ISSUE THREAD

**Issue by zarooba01** [element-hq/element-x-android#3927]
### Your use case

We are from the National Headquarters of the State Fire Service of Poland and we're developing a communication system based on the Element platform in Georgia. This will be an important system in the field of the country's fire safety.
We are missing Georgian translations for web and Android versions. We have already translated all expressions in https://translate.element.io/projects/element-android/element-app/.
Is this sufficient for the translation to work, or is there anything else we need to do?

### Are you willing to provide a PR?

Yes

**Comment by manuroe** [comment]
The link you shared is about translations on Element-Android. This repo is about the new app, Element X Android where we use Localazy as the translation platfom. You can find instructions here: https://github.com/element-hq/element-x-android?tab=readme-ov-file#translations.
