### ISSUE TITLE
If you take a photo in Element X, it doesn't add an extension to the file name causing improper rendering on Web/Desktop

### ISSUE THREAD

**Issue by Twi1ightSparkle** [element-hq/element-x-android#3990]
### Steps to reproduce

- In Element X click `+`, then `Take photo`
- Optionally add a caption
- Send

#### What did you expect?

Properly formatted message

#### What happened instead?

Because of https://github.com/element-hq/element-web/issues/11424, Element Web 1.11.87 doesn't render the image and instead shows it as a file attachment.

![screenshot_2024-12-03T17-01-02Z](https://github.com/user-attachments/assets/ba4b8a7f-4d9e-47c7-b2bc-c1af092f301d)

It also set's the caption as the file name if you try downloading the attachment

![screenshot_2024-12-03T17-01-26Z](https://github.com/user-attachments/assets/b26bd572-0702-4525-9190-1c9f322c6cba)

Element X renders both properly

![1000000286](https://github.com/user-attachments/assets/5a6d7cee-f77f-46e3-a02a-5c932c9258af)

I'll attach the event content to the rageshake. However, looking at the diff, EX doesn't add a file extension to the filename, this might be the reason?

Element Android 1.6.20 also renders both images, but without captions.

Element X iOS 0.7.3 doesn't have this issue, photos taken from within the EX app there works.

### Your phone model

Samsung Galaxy A15

### Operating system version

Android 14

### Application version and app store

Element X 0.7.3

### Homeserver

Sent from element.io to matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by frebib** [comment]
This is an Element Web bug/regression?

**Comment by Twi1ightSparkle** [comment]
> This is an Element Web bug/regression?

Not looked into this more than inspecting the event content, but I suspect it's a combination of EXA needing to add a file extension to the file name and EW should be trying to figure out what a file is based on metadata, not just file name extension (https://github.com/element-hq/element-web/issues/11424)

**Comment by spaetz** [comment]
Should be fixed by https://github.com/element-hq/element-x-android/pull/3903 (probably in the next release)
