### ISSUE TITLE
Statistic collection can't be opt-in

### ISSUE THREAD

**Issue by fauust** [element-hq/element-x-android#4009]
### Steps to reproduce

1. Where are you starting? What can you see?

Install Element X

3. What do you click?

Go to "Usage statistics"

#### What did you expect?

Usage statistics collection is disabled

#### What happened instead?

Usage statistics collection is enabled

See also: https://github.com/thunderbird/thunderbird-android/issues/8199

### Your phone model

pixel5

### Operating system version

LineageOS 21

### Application version and app store

Element X Version 0.7.4

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by spaetz** [comment]
Err, I got asked on first login whether I wanted to enable collecting of data or now, on a full-display screen. Are you sure you never saw that?

**Comment by fauust** [comment]
you are right, sorry for the noise!
