### ISSUE TITLE
Filtering room list lets me enter a multi-line search parameter

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-x-android#606]
### Steps to reproduce

1. Filter room list
2. Type in a search term and hit return

#### What did you expect?
Initiates search

#### What happened instead?
New line is added to the search term field, which will always show no results because it's not possible for a matrix room to have a multi-line name

### Your phone model

Pixel 6a

### Application version and app store

15th June nightly

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by callumu** [comment]
This should just submit the search, not move the user onto a second line of search text

**Comment by kittykat** [comment]
Fixed
