### ISSUE TITLE
SQLite encryption

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#620]
Give a key to the SDK to encrypt it's internal DB.
It must be the key that is currently used for the Crypto Rust SDK in Element Android R.

**Comment by bmarty** [comment]
The passphrase used by Element Android (actually its SDK) to encrypt the Rust crypto store) depends on the `userId`, which is used to compute an alias for the KeyStore ([code](https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/RustEncryptionConfiguration.kt#L33)).

And the Matrix Rust SDK needs the passphrase to configure the [RustAuthenticationService](https://github.com/vector-im/element-x-android/blob/develop/libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/auth/RustMatrixAuthenticationService.kt#L63), i.e. before the app knows about the UserId (before the user login), and also [when restoring a Client](https://github.com/vector-im/element-x-android/blob/develop/libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/auth/RustMatrixAuthenticationService.kt#L82) using `ClientBuilder.passphrase(String)` (at this point we know the userId).

The solution I see for now is to do some preparation work on Element Android: move the existing Key to an alias which does not rely in the userId.

**Comment by bmarty** [comment]
After discussing with @BillCarsonFr it's a bit more complicated to ensure a smooth upgrade from EA to EAx. The database current encryption will need to be changed. Currently the fields are encrypted when inserted and decrypted when read, which is not efficient. So a migration will be needed. Also it will depend if EAr is migrated as well.

The solution could be to pickle DB from EAr and write it to EAx during the upgrade. TBC.

**Comment by spaetz** [comment]
Isbthis what has been done in https://github.com/element-hq/element-x-android/issues/2219?

**Comment by bmarty** [comment]
Yes this have been done in #2244. Actually #2219 was a duplicate of this issue. Thanks!

For future reference:

> The solution I see for now is to do some preparation work on Element Android: move the existing Key to an alias which does not rely in the userId.

See in #2244, actually, the passphrase will be stored by Element Android in the SessionData.
