### ISSUE TITLE
Continued receiving notifications just after signing out

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-x-android#790]
### Steps to reproduce

1. Settings -> Sign out

#### What did you expect?
Stop receiving message notifications immediately

#### What happened instead?
Continue receiving notifications, including message content for at least a few seconds after

### Your phone model

Pixel 6a

### Operating system version

Graphene OS

### Application version and app store

Nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
Just to double check, could you still receive these notifications a few minutes later? I'm asking because If it's just a race condition of a couple of seconds, this could be a minor issue, but if it goes on for minutes it's probably major or critical.

**Comment by kittykat** [comment]
@jmartinesp I think only for a few seconds after logging out. It was long enough that I had time to log out, put my phone now, then it buzzed and when I looked at it much later, I could still read the content on the notification messages.

**Comment by bmarty** [comment]
This should be fixed by #2924.
