### ISSUE TITLE
Add Robolectric test for timeline UI interactions

### ISSUE THREAD

**Issue by jonnyandrew** [element-hq/element-x-android#813]
#### What would you like to do?

Add unit tests (with coverage) for simple interactions in the timeline UI. For example, to check that a click listener is fired in an individual UI component such as the reaction button.

#### Why would you like to do it?

Improve confidence, increase test coverage and improve app stability.

#### How would you like to achieve it?

Using Robolectric + ComposeTestRule

### Have you considered any alternatives?

- Instrumented UI tests - too heavy / too expensive / too flaky / poor developer experience
- Maestro tests - not the right tool for the job / no coverage

### Are you willing to provide a PR?

Yes

**Comment by jmartinesp** [comment]
I found this article, which is probably useful as an example: https://medium.com/@sebaslogen/blazing-fast-compose-tests-with-robolectric-b059f5471495

**Comment by bmarty** [comment]
We are progressively adding test covering UI interaction. I think we can close this issue now.
