### ISSUE TITLE
Align CTA button on login flow.

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#825]
To avoid flickering effect:

![CTA Moving](https://github.com/vector-im/element-x-android/assets/3940906/5f8c27e8-ace4-4a33-b8b8-603f1d2d278a)

Should be more aligned:

<img width="1566" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/916be222-6fc4-49d6-8e8d-84141f65b98e">

**Comment by ankitkumar1302** [comment]
Hello, @bmarty 
I would like to work on it (#825), I am a newbie should you tell me about it or guide me and
I already set up the whole project and ran it on my physical device. now what next..?

**Comment by ankitkumar1302** [comment]
Hello

**Comment by Aditya8840** [comment]
Hi, I would like to work on this issue

**Comment by Umair-Siddique** [comment]
Hi can you please assign this issue to me

I'm on it

**Comment by bmarty** [comment]
Thanks @Umair-Siddique ! WI prefer not assign issue to external contributor, but thanks for letting us know. Expecting a nice PR from you!
