### ISSUE TITLE
Member list in large rooms takes a very long time to load

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-x-android#851]
### Steps to reproduce

1. Go to Matrix HQ
2. Click on the room header, then onto "People"

#### What did you expect?
I can see member list

#### What happened instead?
I see a spinner for at least 15 minutes

### Your phone model

Pixel 6a

### Operating system version

Graphene OS

### Application version and app store

0.1.0-nightly (1001000) - 12th July

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
This is a Rust SDK issue: https://github.com/matrix-org/matrix-rust-sdk/issues/1979

**Comment by jmartinesp** [comment]
I just tested this in a debug build with [this PR](https://github.com/matrix-org/matrix-rust-sdk/pull/3184) in my old test device and the loading times including the network request and response processing time went from 12 minutes in the Matrix HQ room (with ~110.000 users) to 45s. In release mode this should be even faster.

However, we still have an issue with the `/members` request failing and somehow bot being retried again, although according to the Rust code it should. This happened while testing and the only solution for me was to restart the app and then try to reload the member list for the room. I'll open an issue in the Rust SDK repo.

There is also some work needed to be done now to improve the UX of the room member list screen, but that's out of the scope of this issue I believe.
