### ISSUE TITLE
Timeline gets stuck when visiting rooms multiple times

### ISSUE THREAD

**Issue by VolkerJunginger** [element-hq/element-x-android#854]
### Steps to reproduce

- Open the app. From roomlist navigate into a room.
- Leave the room and re-enter.
- Repeat.

After some repeats the timeline gets stuck and is showing a spinner for infinite time.
The user needs to kill the app to stop this behaviour.
The bigger a room the more likely this behaviour can be recognised.

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by manuroe** [comment]
https://github.com/vector-im/element-x-android/pull/863 improves this behavior

**Comment by manuroe** [comment]
One way to reproduce the issue is to open the room member screen. Maybe related to https://github.com/vector-im/element-x-android/issues/851

**Comment by ganfra** [comment]
This was due to deadlock, so this should be fixed for a long time now. Closing.
