### ISSUE TITLE
Implement draft

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#888]
When user type some text in the composer without sending it, the text must be stored locally so that when the user go back to the room list and open the same room again the composer state is restored and the entered text is there, ready to be edited or send.

Ideally the composer mode should also be stored: if the user was replying to, or editing an Event, it must be restored.

Note sure this have to be done at the Matrix SDK level, or by the RichtextEditor (when it will be implemented), or at the application level.

**Comment by witchent** [comment]
https://github.com/matrix-org/matrix-rich-text-editor/issues/650 seems to suggest that this would indeed be implemented at the application level

**Comment by ganfra** [comment]
Replaced by https://github.com/element-hq/element-x-android/issues/2869
