### ISSUE TITLE
F-Droid nigthly repo

### ISSUE THREAD

**Issue by genofire** [element-hq/element-x-android#917]
#### What would you like to do?
Install latest / nightly version per F-Droid app

#### Why would you like to do it?
I do not have any google account

#### How would you like to achieve it?
Wish that vector create an own f-droid repo like:
  - FluffyChat: https://gitlab.com/famedly/fluffychat/-/blob/main/docs/fdroid_repo.md
  - SchildiChat: https://schildi.chat/android/install-from-sc-fdroid-foss/
  - many more

### Are you willing to provide a PR?

No

**Comment by rokejulianlockhart** [comment]
It's also just a better way of testing the APKs currently uploaded to https://github.com/vector-im/element-x-android/releases, especially since F-Droid supports marking releases as unstable.

**Comment by genofire** [comment]
^^ F-Droid support since years marking as unstable ....

**Comment by xethos84** [comment]
> ^^ F-Droid support since years marking as unstable ....

Could you consider sharing a link? I didn't see one when I last looked less than a month ago. Element is available on F-Droid, but nightly Element X builds seem to be missing (or at least are evidently difficult to find)

**Comment by genofire** [comment]
https://f-droid.org/docs/Build_Metadata_Reference/#CurrentVersion just do not set `CurrentVersion` or just set to the latest stable version

**Comment by genofire** [comment]
Releases does not contain apks, just aab. That is not really handy.

**Comment by genofire** [comment]
Jippi, there is apk, now.

**Comment by mcepl** [comment]
On Wed Sep 20, 2023 at 10:48 AM CEST, genofire wrote:
> Jippi, there is apk, now.

Yes, but still nothing on F-Droid. And when I looked on
https://f-droid.org/en/packages/im.vector.app/ I found out that
they claim Element “promotes or depends entirely on a Non-Free
network”. I am used to F-Droid are quite hysteric, excessive, and
useless, but this one doesn’t make sense at all. What part of
https://matrix.org/ they don’t understand?

**Comment by genofire** [comment]
The complete message ist:

> **NonFreeNet**: Each chat has an "Add Matrix apps" button which by default links to the proprietary scalar.vector.im integration manager service.


It is just a policy of f-droid, that menu which default lead somebody to a centralised instance (with an centralize identity server as opt-out).
So some small design change would remove this on f-droid.

---

I did not find it useless and i would like to get Element-X also in the official F-Droid repo) In the End, it is the only good and FOSS appstore (without google or trackern).

So this issue is not about to submit it in the official F-Droid repo. It is just about, to host (or let github-pages host) an repository, to use the standard update function of f-droid. Like it several other App it does (like fluffychat, schildichat as matrix-client or [NewPipe](https://newpipe.net/) and so on).

**Comment by mcepl** [comment]
> I did not find it useless and i would like to get Element-X also in the official F-Droid repo) In the End, it is the only good and FOSS appstore (without google or trackern).

I didn’t mean to say that F-Droid itself is useless, just that their labelling programs as “non-free” is completely out of control (e.g., no Firefox).

> So this issue is not about to submit it in the official F-Droid repo. It is just about, to host (or let github-pages host) an repository, to use the standard update function of f-droid. Like it several other App it does (like fluffychat, schildichat as matrix-client or [NewPipe](https://newpipe.net/) and so on).

OK, and where is the ticket for inclusion into the official F-Droid repo?

**Comment by genofire** [comment]
In #185 they talk to create special buildflavor ... i believe it will not be official released in f-droid, they just wait to replace element for android - but i do not know it

**Comment by shuvashish76** [comment]
> And when I looked on
https://f-droid.org/en/packages/im.vector.app/ I found out that
they claim Element “promotes or depends entirely on a Non-Free
network”. I am used to F-Droid are quite hysteric, excessive, and
useless, but this one doesn’t make sense at all. What part of
https://matrix.org/ they don’t understand?

[This](https://github.com/vector-im/element-android/issues/6898#issuecomment-1657208965) part. Which they never replied. Like many of us, I'm sure it's a surprise for you that their "integration manager" is closed source. Simply adding a warning in the description would remove the AF just like F-Droid removed for SchildiChat.

**Comment by ildar** [comment]
F-Droid RFP: https://gitlab.com/fdroid/rfp/-/issues/2556

**Comment by genofire** [comment]
The fork [SchildiChat-Next](https://github.com/SchildiChat/schildichat-android-next) is in a f-droid repo, now:
https://s2.spiritcroc.de/testing/fdroid/repo?fingerprint=52d03f2fab785573bb295c7ab270695e3a1bdd2adc6a6de8713250b33f231225

**Comment by K4LCIFER** [comment]
[It looks like](https://matrix.org/blog/2024/01/26/this-week-in-matrix-2024-01-26/) Element X is to be published to F-Droid, with support for UnifiedPush, for the release of v0.4.2.

**Comment by Mek101** [comment]
> [It looks like](https://matrix.org/blog/2024/01/26/this-week-in-matrix-2024-01-26/) Element X is to be published to F-Droid, with support for UnifiedPush, for the release of v0.4.2:
> 
> > Next release 0.4.2 should also be published on F-Droid with push support using UnifiedPush.
> 
> Related PR: #2248

Where is it then? More than a month has passed and searching for Element on f-droid only yields the old client and a bunch of unrelated apps

**Comment by K4LCIFER** [comment]
I have absolutely no idea. I don't know why they would announce something and then not follow through.

**Comment by K4LCIFER** [comment]
> Now that we have at least releases on fdroid.org and element stated they have no bandwidth maintaining their own repo, can we close this issue as WONTFIX?

What? I'm confused. Is this issue not closed as completed by https://github.com/element-hq/element-x-android/issues/1418#issuecomment-2155977816?

**Comment by spaetz** [comment]
This issue was about a repository with nightly builds, the fdroid repo only contains releases. That's why this issue has not been really completed.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/element-hq/element-x-android/issues/917#issuecomment-2180329397

@spaetz, is that https://github.com/element-hq/element-x-android/issues/917#issuecomment-1681119770 unacceptable? I'm surprised that this issue's scope was never reduced merely to the publishing of nightly compilations to *an* F-Droid repository, whether self-hosted or official.

**Comment by ara4n** [comment]
we don’t have bandwidth to maintain our own nightly repo. instead we will release early & often.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/element-hq/element-x-android/issues/917#issuecomment-2181257739

@ara4n, I didn't mention that. The cited URI describes you indicating that certain releases are "pre-release" in the official repository.
