### ISSUE TITLE
Local echo for new room picture isn't there

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-x-android#921]
### Steps to reproduce

1. Go to a room where you are admin
2. Change the room avatar
3. Save

#### What did you expect?
I see a local echo of the room avatar when I land back in the room detail view after saving the new photo

#### What happened instead?
I still see a blank picture (there was no room avatar before)

### Your phone model

Pixel 6a

### Operating system version

Graphene OS

### Application version and app store

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Should be possible now that we have https://github.com/matrix-org/matrix-rust-sdk/pull/2411

**Comment by jplatte** [comment]
Well, not so easy. It's the same thing as sending media, we can't have a local echo before the image is uploaded. This will be fixed by the async upload MSC (Synapse PR still pending merge).

**Comment by VolkerJunginger** [comment]
It does not need to be a "local echo". There is already an update of the room happening and the picture has been uploaded. The Android App just deos not update the room-detail screen.

**Comment by jplatte** [comment]
FWIW, asynchronous uploads (which were blocking proper local echoes for media) are shipping in Synapse [v1.97.0](https://github.com/matrix-org/synapse/releases/tag/v1.97.0)+.
